/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of apply.c.
 * Include ONLY from apply.c, after hack.h. */
#ifndef NH_CTX_FILE_APPLY_C_H
#define NH_CTX_FILE_APPLY_C_H
#define jumping_is_magic (nh_cur->g_apply_c_jumping_is_magic)
#define polearm_range_max (nh_cur->g_apply_c_polearm_range_max)
#define polearm_range_min (nh_cur->g_apply_c_polearm_range_min)
#endif /* NH_CTX_FILE_APPLY_C_H */
