/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of artifact.c.
 * Include ONLY from artifact.c, after hack.h. */
#ifndef NH_CTX_FILE_ARTIFACT_C_H
#define NH_CTX_FILE_ARTIFACT_C_H
#define artidisco (nh_cur->g_artifact_c_artidisco)
#define artiexist (nh_cur->g_artifact_c_artiexist)
#define nesting (nh_cur->g_artifact_c_nesting)
#define resbuf (nh_cur->g_artifact_c_resbuf)
#define mkot_trap_warn_count (nh_cur->g_artifact_c_mkot_trap_warn_count)
#define spec_dbon_applies (nh_cur->g_artifact_c_spec_dbon_applies)
#define touch_blasted (nh_cur->g_artifact_c_touch_blasted)
#endif /* NH_CTX_FILE_ARTIFACT_C_H */
