/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of attrib.c.
 * Include ONLY from attrib.c, after hack.h. */
#ifndef NH_CTX_FILE_ATTRIB_C_H
#define NH_CTX_FILE_ATTRIB_C_H
#define from_what_buf (nh_cur->g_attrib_c_from_what_buf)
#endif /* NH_CTX_FILE_ATTRIB_C_H */
