/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of ball.c.
 * Include ONLY from ball.c, after hack.h. */
#ifndef NH_CTX_FILE_BALL_C_H
#define NH_CTX_FILE_BALL_C_H
#define bcp_p (nh_cur->g_ball_c_bcp_p)
#define bcu_p (nh_cur->g_ball_c_bcu_p)
#define bcrestriction (nh_cur->g_ball_c_bcrestriction)
#endif /* NH_CTX_FILE_BALL_C_H */
