/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dbridge.c.
 * Include ONLY from dbridge.c, after hack.h. */
#ifndef NH_CTX_FILE_DBRIDGE_C_H
#define NH_CTX_FILE_DBRIDGE_C_H
#define wholebuf (nh_cur->g_dbridge_c_wholebuf)
#define occupants_p (nh_cur->g_dbridge_c_occupants_p)
#endif /* NH_CTX_FILE_DBRIDGE_C_H */
