/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dig.c.
 * Include ONLY from dig.c, after hack.h. */
#ifndef NH_CTX_FILE_DIG_C_H
#define NH_CTX_FILE_DIG_C_H
#define did_dig_msg (nh_cur->g_dig_c_did_dig_msg)
#endif /* NH_CTX_FILE_DIG_C_H */
