/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of display.c.
 * Include ONLY from display.c, after hack.h. */
#ifndef NH_CTX_FILE_DISPLAY_C_H
#define NH_CTX_FILE_DISPLAY_C_H
#define gbuf_start (nh_cur->g_display_c_gbuf_start)
#define gbuf_stop (nh_cur->g_display_c_gbuf_stop)
#define bad_count (nh_cur->g_display_c_bad_count)
#define tglyph_p (nh_cur->g_display_c_tglyph_p)
#define in_cls (nh_cur->g_display_c_in_cls)
#define flushing (nh_cur->g_display_c_flushing)
#define delay_flushing (nh_cur->g_display_c_delay_flushing)
#define swallowed_lastx (nh_cur->g_display_c_swallowed_lastx)
#define swallowed_lasty (nh_cur->g_display_c_swallowed_lasty)
#define under_water_lastx (nh_cur->g_display_c_under_water_lastx)
#define under_water_lasty (nh_cur->g_display_c_under_water_lasty)
#define under_water_dela (nh_cur->g_display_c_under_water_dela)
#define under_ground_dela (nh_cur->g_display_c_under_ground_dela)
#define nul_gbuf_new (nh_cur->g_display_c_nul_gbuf_new)
#define nul_gbuf_glyph (nh_cur->g_display_c_nul_gbuf_glyph)
#endif /* NH_CTX_FILE_DISPLAY_C_H */
