/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dlb.c.
 * Include ONLY from dlb.c, after hack.h. */
#ifndef NH_CTX_FILE_DLB_C_H
#define NH_CTX_FILE_DLB_C_H
#define initialized (nh_cur->g_dlb_c_initialized)
#endif /* NH_CTX_FILE_DLB_C_H */
