/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of do.c.
 * Include ONLY from do.c, after hack.h. */
#ifndef NH_CTX_FILE_DO_C_H
#define NH_CTX_FILE_DO_C_H
#define at_ladder (nh_cur->g_do_c_at_ladder)
#define dfr_post_msg (nh_cur->g_do_c_dfr_post_msg)
#define dfr_pre_msg (nh_cur->g_do_c_dfr_pre_msg)
#define dowipe_buf (nh_cur->g_do_c_dowipe_buf)
#define save_dlevel_store (nh_cur->g_do_c_save_dlevel_store)
#endif /* NH_CTX_FILE_DO_C_H */
