/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of do_name.c.
 * Include ONLY from do_name.c, after hack.h. */
#ifndef NH_CTX_FILE_DO_NAME_C_H
#define NH_CTX_FILE_DO_NAME_C_H
#define dxdy_buf (nh_cur->g_do_name_c_dxdy_buf)
#define rndmonnam_buf (nh_cur->g_do_name_c_rndmonnam_buf)
#define gloc_filter_match_glyph (nh_cur->g_do_name_c_gloc_filter_match_glyph)
#define gloc_filter_map_p (nh_cur->g_do_name_c_gloc_filter_map_p)
#define mbuf_idx (nh_cur->g_do_name_c_mbuf_idx)
#define mbufs (nh_cur->g_do_name_c_mbufs)
#define via_naming (nh_cur->g_do_name_c_via_naming)
#endif /* NH_CTX_FILE_DO_NAME_C_H */
