/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of do_wear.c.
 * Include ONLY from do_wear.c, after hack.h. */
#ifndef NH_CTX_FILE_DO_WEAR_C_H
#define NH_CTX_FILE_DO_WEAR_C_H
#define offdelaybuf (nh_cur->g_do_wear_c_offdelaybuf)
#define initial_don (nh_cur->g_do_wear_c_initial_don)
#endif /* NH_CTX_FILE_DO_WEAR_C_H */
