/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dog.c.
 * Include ONLY from dog.c, after hack.h. */
#ifndef NH_CTX_FILE_DOG_C_H
#define NH_CTX_FILE_DOG_C_H
#define petname_used (nh_cur->g_dog_c_petname_used)
#endif /* NH_CTX_FILE_DOG_C_H */
