/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dogmove.c.
 * Include ONLY from dogmove.c, after hack.h. */
#ifndef NH_CTX_FILE_DOGMOVE_C_H
#define NH_CTX_FILE_DOGMOVE_C_H
#define gtyp (nh_cur->g_dogmove_c_gtyp)
#define gx (nh_cur->g_dogmove_c_gx)
#define gy (nh_cur->g_dogmove_c_gy)
#endif /* NH_CTX_FILE_DOGMOVE_C_H */
