/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dothrow.c.
 * Include ONLY from dothrow.c, after hack.h. */
#ifndef NH_CTX_FILE_DOTHROW_C_H
#define NH_CTX_FILE_DOTHROW_C_H
#define breakobj_lastmovetime (nh_cur->g_dothrow_c_breakobj_lastmovetime)
#define breakobj_peaceful_shk (nh_cur->g_dothrow_c_breakobj_peaceful_shk)
#endif /* NH_CTX_FILE_DOTHROW_C_H */
