/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of drawing.c.
 * Include ONLY from drawing.c, after hack.h. */
#ifndef NH_CTX_FILE_DRAWING_C_H
#define NH_CTX_FILE_DRAWING_C_H
#define currentgraphics (nh_cur->g_drawing_c_currentgraphics)
#endif /* NH_CTX_FILE_DRAWING_C_H */
