/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of dungeon.c.
 * Include ONLY from dungeon.c, after hack.h. */
#ifndef NH_CTX_FILE_DUNGEON_C_H
#define NH_CTX_FILE_DUNGEON_C_H
#define n_dgns (nh_cur->g_dungeon_c_n_dgns)
#endif /* NH_CTX_FILE_DUNGEON_C_H */
