/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of eat.c.
 * Include ONLY from eat.c, after hack.h. */
#ifndef NH_CTX_FILE_EAT_C_H
#define NH_CTX_FILE_EAT_C_H
#define force_save_hs (nh_cur->g_eat_c_force_save_hs)
#define msgbuf (nh_cur->g_eat_c_msgbuf)
#define ate_brains (nh_cur->g_eat_c_ate_brains)
#define newuhs_save_hs (nh_cur->g_eat_c_newuhs_save_hs)
#define newuhs_saved_hs (nh_cur->g_eat_c_newuhs_saved_hs)
#endif /* NH_CTX_FILE_EAT_C_H */
