/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of end.c.
 * Include ONLY from end.c, after hack.h. */
#ifndef NH_CTX_FILE_END_C_H
#define NH_CTX_FILE_END_C_H
#define vanq_sortmode (nh_cur->g_end_c_vanq_sortmode)
#endif /* NH_CTX_FILE_END_C_H */
