/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of engrave.c.
 * Include ONLY from engrave.c, after hack.h. */
#ifndef NH_CTX_FILE_ENGRAVE_C_H
#define NH_CTX_FILE_ENGRAVE_C_H
#define head_engr (nh_cur->g_engrave_c_head_engr)
#endif /* NH_CTX_FILE_ENGRAVE_C_H */
