/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of extralev.c.
 * Include ONLY from extralev.c, after hack.h. */
#ifndef NH_CTX_FILE_EXTRALEV_C_H
#define NH_CTX_FILE_EXTRALEV_C_H
#define r_p (nh_cur->g_extralev_c_r_p)
#endif /* NH_CTX_FILE_EXTRALEV_C_H */
