/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of files.c.
 * Include ONLY from files.c, after hack.h. */
#ifndef NH_CTX_FILE_FILES_C_H
#define NH_CTX_FILE_FILES_C_H
#define savef (nh_cur->g_files_c_savef)
#define bones (nh_cur->g_files_c_bones)
#define config_section_chosen (nh_cur->g_files_c_config_section_chosen)
#define config_section_current (nh_cur->g_files_c_config_section_current)
#define fqn_fname (nh_cur->g_files_c_fqn_fname)
#define lockptr (nh_cur->g_files_c_lockptr)
#define wizkit (nh_cur->g_files_c_wizkit)
#define lock (nh_cur->g_files_c_lock)
#define chosen_symset_start (nh_cur->g_files_c_chosen_symset_start)
#define chosen_symset_end (nh_cur->g_files_c_chosen_symset_end)
#endif /* NH_CTX_FILE_FILES_C_H */
