/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of getline.c.
 * Include ONLY from getline.c, after hack.h. */
#ifndef NH_CTX_FILE_GETLINE_C_H
#define NH_CTX_FILE_GETLINE_C_H
#define suppress_history (nh_cur->g_getline_c_suppress_history)
#endif /* NH_CTX_FILE_GETLINE_C_H */
