/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of hack.c.
 * Include ONLY from hack.c, after hack.h. */
#ifndef NH_CTX_FILE_HACK_C_H
#define NH_CTX_FILE_HACK_C_H
#define domove_skates (nh_cur->g_hack_c_domove_skates)
#define in_rooms_buf (nh_cur->g_hack_c_in_rooms_buf)
#define inspoteffects (nh_cur->g_hack_c_inspoteffects)
#define moverock_lastmovetime (nh_cur->g_hack_c_moverock_lastmovetime)
#define spotloc_x (nh_cur->g_hack_c_spotloc_x)
#define spotloc_y (nh_cur->g_hack_c_spotloc_y)
#define spotterrain (nh_cur->g_hack_c_spotterrain)
#define spottrap (nh_cur->g_hack_c_spottrap)
#define spottraptyp (nh_cur->g_hack_c_spottraptyp)
#define tmp_anything_p (nh_cur->g_hack_c_tmp_anything_p)
#define wc (nh_cur->g_hack_c_wc)
#endif /* NH_CTX_FILE_HACK_C_H */
