/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of invent.c.
 * Include ONLY from invent.c, after hack.h. */
#ifndef NH_CTX_FILE_INVENT_C_H
#define NH_CTX_FILE_INVENT_C_H
#define lastinvnr (nh_cur->g_invent_c_lastinvnr)
#define sortlootmode (nh_cur->g_invent_c_sortlootmode)
#define cached_pickinv_win (nh_cur->g_invent_c_cached_pickinv_win)
#define this_type (nh_cur->g_invent_c_this_type)
#define invbufsiz (nh_cur->g_invent_c_invbufsiz)
#define only_x (nh_cur->g_invent_c_only_x)
#define only_y (nh_cur->g_invent_c_only_y)
#define safeq_xprn_let (nh_cur->g_invent_c_safeq_xprn_let)
#define safeq_xprn_dot (nh_cur->g_invent_c_safeq_xprn_dot)
#define armcat (nh_cur->g_invent_c_armcat)
#define li (nh_cur->g_invent_c_li)
#define altbuf (nh_cur->g_invent_c_altbuf)
#endif /* NH_CTX_FILE_INVENT_C_H */
