/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of light.c.
 * Include ONLY from light.c, after hack.h. */
#ifndef NH_CTX_FILE_LIGHT_C_H
#define NH_CTX_FILE_LIGHT_C_H
#define light_base (nh_cur->g_light_c_light_base)
#endif /* NH_CTX_FILE_LIGHT_C_H */
