/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of lock.c.
 * Include ONLY from lock.c, after hack.h. */
#ifndef NH_CTX_FILE_LOCK_C_H
#define NH_CTX_FILE_LOCK_C_H
#define xlock_door_p (nh_cur->g_lock_c_xlock_door_p)
#endif /* NH_CTX_FILE_LOCK_C_H */
