/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of makemon.c.
 * Include ONLY from makemon.c, after hack.h. */
#ifndef NH_CTX_FILE_MAKEMON_C_H
#define NH_CTX_FILE_MAKEMON_C_H
#define align_shift_lev_p (nh_cur->g_makemon_c_align_shift_lev_p)
#define align_shift_oldmoves (nh_cur->g_makemon_c_align_shift_oldmoves)
#endif /* NH_CTX_FILE_MAKEMON_C_H */
