/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mapglyph.c.
 * Include ONLY from mapglyph.c, after hack.h. */
#ifndef NH_CTX_FILE_MAPGLYPH_C_H
#define NH_CTX_FILE_MAPGLYPH_C_H
#define encbuf (nh_cur->g_mapglyph_c_encbuf)
#endif /* NH_CTX_FILE_MAPGLYPH_C_H */
