/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mhitm.c.
 * Include ONLY from mhitm.c, after hack.h. */
#ifndef NH_CTX_FILE_MHITM_C_H
#define NH_CTX_FILE_MHITM_C_H
#define dieroll (nh_cur->g_mhitm_c_dieroll)
#define far_noise (nh_cur->g_mhitm_c_far_noise)
#define otmp (nh_cur->g_mhitm_c_otmp)
#define noisetime (nh_cur->g_mhitm_c_noisetime)
#define vis (nh_cur->g_mhitm_c_vis)
#endif /* NH_CTX_FILE_MHITM_C_H */
