/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mhitu.c.
 * Include ONLY from mhitu.c, after hack.h. */
#ifndef NH_CTX_FILE_MHITU_C_H
#define NH_CTX_FILE_MHITU_C_H
#define dieroll (nh_cur->g_mhitu_c_dieroll)
#define mon_currwep (nh_cur->g_mhitu_c_mon_currwep)
#endif /* NH_CTX_FILE_MHITU_C_H */
