/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mklev.c.
 * Include ONLY from mklev.c, after hack.h. */
#ifndef NH_CTX_FILE_MKLEV_C_H
#define NH_CTX_FILE_MKLEV_C_H
#define made_branch (nh_cur->g_mklev_c_made_branch)
#define vault_x (nh_cur->g_mklev_c_vault_x)
#define vault_y (nh_cur->g_mklev_c_vault_y)
#endif /* NH_CTX_FILE_MKLEV_C_H */
