/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mkmap.c.
 * Include ONLY from mkmap.c, after hack.h. */
#ifndef NH_CTX_FILE_MKMAP_C_H
#define NH_CTX_FILE_MKMAP_C_H
#define n_loc_filled (nh_cur->g_mkmap_c_n_loc_filled)
#endif /* NH_CTX_FILE_MKMAP_C_H */
