/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mkmaze.c.
 * Include ONLY from mkmaze.c, after hack.h. */
#ifndef NH_CTX_FILE_MKMAZE_C_H
#define NH_CTX_FILE_MKMAZE_C_H
#define bbubbles (nh_cur->g_mkmaze_c_bbubbles)
#define ebubbles (nh_cur->g_mkmaze_c_ebubbles)
#define movebubbles_up (nh_cur->g_mkmaze_c_movebubbles_up)
#define water_xmin (nh_cur->g_mkmaze_c_water_xmin)
#define water_ymin (nh_cur->g_mkmaze_c_water_ymin)
#define water_xmax (nh_cur->g_mkmaze_c_water_xmax)
#define water_ymax (nh_cur->g_mkmaze_c_water_ymax)
#define wportal (nh_cur->g_mkmaze_c_wportal)
#endif /* NH_CTX_FILE_MKMAZE_C_H */
