/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mkobj.c.
 * Include ONLY from mkobj.c, after hack.h. */
#ifndef NH_CTX_FILE_MKOBJ_C_H
#define NH_CTX_FILE_MKOBJ_C_H
#define unknown (nh_cur->g_mkobj_c_unknown)
#endif /* NH_CTX_FILE_MKOBJ_C_H */
