/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mkroom.c.
 * Include ONLY from mkroom.c, after hack.h. */
#ifndef NH_CTX_FILE_MKROOM_C_H
#define NH_CTX_FILE_MKROOM_C_H
#define shrine_buf (nh_cur->g_mkroom_c_shrine_buf)
#endif /* NH_CTX_FILE_MKROOM_C_H */
