/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mon.c.
 * Include ONLY from mon.c, after hack.h. */
#ifndef NH_CTX_FILE_MON_C_H
#define NH_CTX_FILE_MON_C_H
#define animal_list_count (nh_cur->g_mon_c_animal_list_count)
#define disintegested (nh_cur->g_mon_c_disintegested)
#define elemental_clog_msgmv (nh_cur->g_mon_c_elemental_clog_msgmv)
#define vamp_rise_msg (nh_cur->g_mon_c_vamp_rise_msg)
#endif /* NH_CTX_FILE_MON_C_H */
