/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of mthrowu.c.
 * Include ONLY from mthrowu.c, after hack.h. */
#ifndef NH_CTX_FILE_MTHROWU_C_H
#define NH_CTX_FILE_MTHROWU_C_H
#define mesg_given (nh_cur->g_mthrowu_c_mesg_given)
#define archer (nh_cur->g_mthrowu_c_archer)
#define target (nh_cur->g_mthrowu_c_target)
#endif /* NH_CTX_FILE_MTHROWU_C_H */
