/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of muse.c.
 * Include ONLY from muse.c, after hack.h. */
#ifndef NH_CTX_FILE_MUSE_C_H
#define NH_CTX_FILE_MUSE_C_H
#define m_using (nh_cur->g_muse_c_m_using)
#define trapx (nh_cur->g_muse_c_trapx)
#define trapy (nh_cur->g_muse_c_trapy)
#define zap_oseen (nh_cur->g_muse_c_zap_oseen)
#endif /* NH_CTX_FILE_MUSE_C_H */
