/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of nlernd.c.
 * Include ONLY from nlernd.c, after hack.h. */
#ifndef NH_CTX_FILE_NLERND_C_H
#define NH_CTX_FILE_NLERND_C_H
#define lgen_base (nh_cur->g_nlernd_c_lgen_base)
#define lgen_state (nh_cur->g_nlernd_c_lgen_state)
#define core_state (nh_cur->g_nlernd_c_core_state)
#define lgen_initialised (nh_cur->g_nlernd_c_lgen_initialised)
#define lgen_active (nh_cur->g_nlernd_c_lgen_active)
#endif /* NH_CTX_FILE_NLERND_C_H */
