/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of o_init.c.
 * Include ONLY from o_init.c, after hack.h. */
#ifndef NH_CTX_FILE_O_INIT_C_H
#define NH_CTX_FILE_O_INIT_C_H
#define disco (nh_cur->g_o_init_c_disco)
#endif /* NH_CTX_FILE_O_INIT_C_H */
