/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of objnam.c.
 * Include ONLY from objnam.c, after hack.h. */
#ifndef NH_CTX_FILE_OBJNAM_C_H
#define NH_CTX_FILE_OBJNAM_C_H
#define obufs (nh_cur->g_objnam_c_obufs)
#endif /* NH_CTX_FILE_OBJNAM_C_H */
