/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of options.c.
 * Include ONLY from options.c, after hack.h. */
#ifndef NH_CTX_FILE_OPTIONS_C_H
#define NH_CTX_FILE_OPTIONS_C_H
#define n_menu_mapped (nh_cur->g_options_c_n_menu_mapped)
#endif /* NH_CTX_FILE_OPTIONS_C_H */
