/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of pickup.c.
 * Include ONLY from pickup.c, after hack.h. */
#ifndef NH_CTX_FILE_PICKUP_C_H
#define NH_CTX_FILE_PICKUP_C_H
#define abort_looting (nh_cur->g_pickup_c_abort_looting)
#define autopick_costly (nh_cur->g_pickup_c_autopick_costly)
#define bucx_filter (nh_cur->g_pickup_c_bucx_filter)
#define class_filter (nh_cur->g_pickup_c_class_filter)
#define current_container (nh_cur->g_pickup_c_current_container)
#define encumber_msg_oldcap (nh_cur->g_pickup_c_encumber_msg_oldcap)
#define shop_filter (nh_cur->g_pickup_c_shop_filter)
#define val_for_n_or_more (nh_cur->g_pickup_c_val_for_n_or_more)
#define valid_menu_classes (nh_cur->g_pickup_c_valid_menu_classes)
#define vmc_count (nh_cur->g_pickup_c_vmc_count)
#endif /* NH_CTX_FILE_PICKUP_C_H */
