/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of pline.c.
 * Include ONLY from pline.c, after hack.h. */
#ifndef NH_CTX_FILE_PLINE_C_H
#define NH_CTX_FILE_PLINE_C_H
#define pline_flags (nh_cur->g_pline_c_pline_flags)
#define in_pline (nh_cur->g_pline_c_in_pline)
#define prevmsg (nh_cur->g_pline_c_prevmsg)
#endif /* NH_CTX_FILE_PLINE_C_H */
