/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of polyself.c.
 * Include ONLY from polyself.c, after hack.h. */
#ifndef NH_CTX_FILE_POLYSELF_C_H
#define NH_CTX_FILE_POLYSELF_C_H
#define sex_change_ok (nh_cur->g_polyself_c_sex_change_ok)
#endif /* NH_CTX_FILE_POLYSELF_C_H */
