/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of potion.c.
 * Include ONLY from potion.c, after hack.h. */
#ifndef NH_CTX_FILE_POTION_C_H
#define NH_CTX_FILE_POTION_C_H
#define nothing (nh_cur->g_potion_c_nothing)
#define unkn (nh_cur->g_potion_c_unkn)
#endif /* NH_CTX_FILE_POTION_C_H */
