/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of pray.c.
 * Include ONLY from pray.c, after hack.h. */
#ifndef NH_CTX_FILE_PRAY_C_H
#define NH_CTX_FILE_PRAY_C_H
#define p_aligntyp (nh_cur->g_pray_c_p_aligntyp)
#define p_trouble (nh_cur->g_pray_c_p_trouble)
#define p_type (nh_cur->g_pray_c_p_type)
#endif /* NH_CTX_FILE_PRAY_C_H */
