/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of priest.c.
 * Include ONLY from priest.c, after hack.h. */
#ifndef NH_CTX_FILE_PRIEST_C_H
#define NH_CTX_FILE_PRIEST_C_H
#define piousness_buf (nh_cur->g_priest_c_piousness_buf)
#endif /* NH_CTX_FILE_PRIEST_C_H */
