/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of questpgr.c.
 * Include ONLY from questpgr.c, after hack.h. */
#ifndef NH_CTX_FILE_QUESTPGR_C_H
#define NH_CTX_FILE_QUESTPGR_C_H
#define cvt_buf (nh_cur->g_questpgr_c_cvt_buf)
#define nambuf (nh_cur->g_questpgr_c_nambuf)
#define msg_file_p (nh_cur->g_questpgr_c_msg_file_p)
#endif /* NH_CTX_FILE_QUESTPGR_C_H */
