/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of read.c.
 * Include ONLY from read.c, after hack.h. */
#ifndef NH_CTX_FILE_READ_C_H
#define NH_CTX_FILE_READ_C_H
#define gremlins_p (nh_cur->g_read_c_gremlins_p)
#define known (nh_cur->g_read_c_known)
#endif /* NH_CTX_FILE_READ_C_H */
