/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of rect.c.
 * Include ONLY from rect.c, after hack.h. */
#ifndef NH_CTX_FILE_RECT_C_H
#define NH_CTX_FILE_RECT_C_H
#define rect_cnt (nh_cur->g_rect_c_rect_cnt)
#endif /* NH_CTX_FILE_RECT_C_H */
