/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of region.c.
 * Include ONLY from region.c, after hack.h. */
#ifndef NH_CTX_FILE_REGION_C_H
#define NH_CTX_FILE_REGION_C_H
#define regions_p (nh_cur->g_region_c_regions_p)
#define n_regions (nh_cur->g_region_c_n_regions)
#define max_regions (nh_cur->g_region_c_max_regions)
#endif /* NH_CTX_FILE_REGION_C_H */
