/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of restore.c.
 * Include ONLY from restore.c, after hack.h. */
#ifndef NH_CTX_FILE_RESTORE_C_H
#define NH_CTX_FILE_RESTORE_C_H
#define id_map_p (nh_cur->g_restore_c_id_map_p)
#define n_ids_mapped (nh_cur->g_restore_c_n_ids_mapped)
#define oldfruit (nh_cur->g_restore_c_oldfruit)
#define omoves (nh_cur->g_restore_c_omoves)
#define procs_mread_flags (nh_cur->g_restore_c_procs_mread_flags)
#define procs_name (nh_cur->g_restore_c_procs_name)
#define procs_bclose (nh_cur->g_restore_c_procs_bclose)
#define procs_minit (nh_cur->g_restore_c_procs_minit)
#define procs_mread (nh_cur->g_restore_c_procs_mread)
#define zc_inbuf (nh_cur->g_restore_c_zc_inbuf)
#define zc_inrunlength (nh_cur->g_restore_c_zc_inrunlength)
#define zc_mreadfd (nh_cur->g_restore_c_zc_mreadfd)
#endif /* NH_CTX_FILE_RESTORE_C_H */
