/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of role.c.
 * Include ONLY from role.c, after hack.h. */
#ifndef NH_CTX_FILE_ROLE_C_H
#define NH_CTX_FILE_ROLE_C_H
#define pa (nh_cur->g_role_c_pa)
#define post_attribs (nh_cur->g_role_c_post_attribs)
#define urole_store (nh_cur->g_role_c_urole_store)
#define urace_store (nh_cur->g_role_c_urace_store)
#endif /* NH_CTX_FILE_ROLE_C_H */
