/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of rumors.c.
 * Include ONLY from rumors.c, after hack.h. */
#ifndef NH_CTX_FILE_RUMORS_C_H
#define NH_CTX_FILE_RUMORS_C_H
#define oracle_flg (nh_cur->g_rumors_c_oracle_flg)
#define oracle_cnt (nh_cur->g_rumors_c_oracle_cnt)
#define true_rumor_size (nh_cur->g_rumors_c_true_rumor_size)
#endif /* NH_CTX_FILE_RUMORS_C_H */
