/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of save.c.
 * Include ONLY from save.c, after hack.h. */
#ifndef NH_CTX_FILE_SAVE_C_H
#define NH_CTX_FILE_SAVE_C_H
#define bw_file (nh_cur->g_save_c_bw_file)
#define bwritefd (nh_cur->g_save_c_bwritefd)
#define compressing (nh_cur->g_save_c_compressing)
#define count_only (nh_cur->g_save_c_count_only)
#define outbuf (nh_cur->g_save_c_outbuf)
#define outbufp (nh_cur->g_save_c_outbufp)
#define outrunlength (nh_cur->g_save_c_outrunlength)
#define procs_name (nh_cur->g_save_c_procs_name)
#define procs_bclose (nh_cur->g_save_c_procs_bclose)
#define procs_bflush (nh_cur->g_save_c_procs_bflush)
#define procs_bufoff (nh_cur->g_save_c_procs_bufoff)
#define procs_bufon (nh_cur->g_save_c_procs_bufon)
#define procs_bwrite (nh_cur->g_save_c_procs_bwrite)
#define usteed_id (nh_cur->g_save_c_usteed_id)
#define ustuck_id (nh_cur->g_save_c_ustuck_id)
#endif /* NH_CTX_FILE_SAVE_C_H */
