/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of shk.c.
 * Include ONLY from shk.c, after hack.h. */
#ifndef NH_CTX_FILE_SHK_C_H
#define NH_CTX_FILE_SHK_C_H
#define pickmovetime (nh_cur->g_shk_c_pickmovetime)
#define empty_shops (nh_cur->g_shk_c_empty_shops)
#endif /* NH_CTX_FILE_SHK_C_H */
