/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of sp_lev.c.
 * Include ONLY from sp_lev.c, after hack.h. */
#ifndef NH_CTX_FILE_SP_LEV_C_H
#define NH_CTX_FILE_SP_LEV_C_H
#define min_rx (nh_cur->g_sp_lev_c_min_rx)
#define max_rx (nh_cur->g_sp_lev_c_max_rx)
#define min_ry (nh_cur->g_sp_lev_c_min_ry)
#define max_ry (nh_cur->g_sp_lev_c_max_ry)
#define splev_map (nh_cur->g_sp_lev_c_splev_map)
#define xstart (nh_cur->g_sp_lev_c_xstart)
#define ystart (nh_cur->g_sp_lev_c_ystart)
#define xsize (nh_cur->g_sp_lev_c_xsize)
#define ysize (nh_cur->g_sp_lev_c_ysize)
#define lev_message (nh_cur->g_sp_lev_c_lev_message)
#define lregions_p (nh_cur->g_sp_lev_c_lregions_p)
#define num_lregions (nh_cur->g_sp_lev_c_num_lregions)
#define splev_init_present (nh_cur->g_sp_lev_c_splev_init_present)
#define icedpools (nh_cur->g_sp_lev_c_icedpools)
#define container_idx (nh_cur->g_sp_lev_c_container_idx)
#define container_obj (nh_cur->g_sp_lev_c_container_obj)
#define invent_carrying_monster (nh_cur->g_sp_lev_c_invent_carrying_monster)
#define mines_prize_count (nh_cur->g_sp_lev_c_mines_prize_count)
#define soko_prize_count (nh_cur->g_sp_lev_c_soko_prize_count)
#define floodfillchk_match_under_typ (nh_cur->g_sp_lev_c_floodfillchk_match_under_typ)
#define ralign (nh_cur->g_sp_lev_c_ralign)
#endif /* NH_CTX_FILE_SP_LEV_C_H */
