/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of spell.c.
 * Include ONLY from spell.c, after hack.h. */
#ifndef NH_CTX_FILE_SPELL_C_H
#define NH_CTX_FILE_SPELL_C_H
#define sortmode (nh_cur->g_spell_c_sortmode)
#endif /* NH_CTX_FILE_SPELL_C_H */
