/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of steal.c.
 * Include ONLY from steal.c, after hack.h. */
#ifndef NH_CTX_FILE_STEAL_C_H
#define NH_CTX_FILE_STEAL_C_H
#define stealmid (nh_cur->g_steal_c_stealmid)
#define stealoid (nh_cur->g_steal_c_stealoid)
#endif /* NH_CTX_FILE_STEAL_C_H */
