/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of teleport.c.
 * Include ONLY from teleport.c, after hack.h. */
#ifndef NH_CTX_FILE_TELEPORT_C_H
#define NH_CTX_FILE_TELEPORT_C_H
#define telescroll (nh_cur->g_teleport_c_telescroll)
#endif /* NH_CTX_FILE_TELEPORT_C_H */
