/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of timeout.c.
 * Include ONLY from timeout.c, after hack.h. */
#ifndef NH_CTX_FILE_TIMEOUT_C_H
#define NH_CTX_FILE_TIMEOUT_C_H
#define timer_base (nh_cur->g_timeout_c_timer_base)
#define timer_id (nh_cur->g_timeout_c_timer_id)
#endif /* NH_CTX_FILE_TIMEOUT_C_H */
