/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of topl.c.
 * Include ONLY from topl.c, after hack.h. */
#ifndef NH_CTX_FILE_TOPL_C_H
#define NH_CTX_FILE_TOPL_C_H
#define initd (nh_cur->g_topl_c_initd)
#define nxtidx (nh_cur->g_topl_c_nxtidx)
#endif /* NH_CTX_FILE_TOPL_C_H */
