/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of topten.c.
 * Include ONLY from topten.c, after hack.h. */
#ifndef NH_CTX_FILE_TOPTEN_C_H
#define NH_CTX_FILE_TOPTEN_C_H
#define final_fpos (nh_cur->g_topten_c_final_fpos)
#define tt_buf_p (nh_cur->g_topten_c_tt_buf_p)
#define toptenwin (nh_cur->g_topten_c_toptenwin)
#define tt_head_p (nh_cur->g_topten_c_tt_head_p)
#endif /* NH_CTX_FILE_TOPTEN_C_H */
