/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of track.c.
 * Include ONLY from track.c, after hack.h. */
#ifndef NH_CTX_FILE_TRACK_C_H
#define NH_CTX_FILE_TRACK_C_H
#define utcnt (nh_cur->g_track_c_utcnt)
#define utpnt (nh_cur->g_track_c_utpnt)
#define utrack (nh_cur->g_track_c_utrack)
#endif /* NH_CTX_FILE_TRACK_C_H */
