/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of trap.c.
 * Include ONLY from trap.c, after hack.h. */
#ifndef NH_CTX_FILE_TRAP_C_H
#define NH_CTX_FILE_TRAP_C_H
#define tnbuf (nh_cur->g_trap_c_tnbuf)
#define force_mintrap (nh_cur->g_trap_c_force_mintrap)
#define recursive_mine (nh_cur->g_trap_c_recursive_mine)
#endif /* NH_CTX_FILE_TRAP_C_H */
