/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of uhitm.c.
 * Include ONLY from uhitm.c, after hack.h. */
#ifndef NH_CTX_FILE_UHITM_C_H
#define NH_CTX_FILE_UHITM_C_H
#define cleave_clockwise (nh_cur->g_uhitm_c_cleave_clockwise)
#define msgbuf (nh_cur->g_uhitm_c_msgbuf)
#endif /* NH_CTX_FILE_UHITM_C_H */
