/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of vision.c.
 * Include ONLY from vision.c, after hack.h. */
#ifndef NH_CTX_FILE_VISION_C_H
#define NH_CTX_FILE_VISION_C_H
#define could_see (nh_cur->g_vision_c_could_see)
#define viz_clear (nh_cur->g_vision_c_viz_clear)
#define left_ptrs (nh_cur->g_vision_c_left_ptrs)
#define right_ptrs (nh_cur->g_vision_c_right_ptrs)
#define viz_clear_rows (nh_cur->g_vision_c_viz_clear_rows)
#define cs_rows0 (nh_cur->g_vision_c_cs_rows0)
#define cs_rows1 (nh_cur->g_vision_c_cs_rows1)
#define cs_rmin0 (nh_cur->g_vision_c_cs_rmin0)
#define cs_rmax0 (nh_cur->g_vision_c_cs_rmax0)
#define cs_rmin1 (nh_cur->g_vision_c_cs_rmin1)
#define cs_rmax1 (nh_cur->g_vision_c_cs_rmax1)
#define viz_rmin (nh_cur->g_vision_c_viz_rmin)
#define viz_rmax (nh_cur->g_vision_c_viz_rmax)
#define vis_start_row (nh_cur->g_vision_c_vis_start_row)
#define vis_start_col (nh_cur->g_vision_c_vis_start_col)
#define vis_step (nh_cur->g_vision_c_vis_step)
#define vis_cs_rows (nh_cur->g_vision_c_vis_cs_rows)
#define vis_cs_left (nh_cur->g_vision_c_vis_cs_left)
#define vis_cs_right (nh_cur->g_vision_c_vis_cs_right)
#define vis_func (nh_cur->g_vision_c_vis_func)
#define vis_varg (nh_cur->g_vision_c_vis_varg)
#define vision_recur_depth (nh_cur->g_vision_c_vision_recur_depth)
#define vision_colbump (nh_cur->g_vision_c_vision_colbump)
#endif /* NH_CTX_FILE_VISION_C_H */
