/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of weapon.c.
 * Include ONLY from weapon.c, after hack.h. */
#ifndef NH_CTX_FILE_WEAPON_C_H
#define NH_CTX_FILE_WEAPON_C_H
#define propellor (nh_cur->g_weapon_c_propellor)
#endif /* NH_CTX_FILE_WEAPON_C_H */
