/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of windows.c.
 * Include ONLY from windows.c, after hack.h. */
#ifndef NH_CTX_FILE_WINDOWS_C_H
#define NH_CTX_FILE_WINDOWS_C_H
#define last_winchoice (nh_cur->g_windows_c_last_winchoice)
#define status_activefields (nh_cur->g_windows_c_status_activefields)
#define status_fieldfmt (nh_cur->g_windows_c_status_fieldfmt)
#define status_fieldnm (nh_cur->g_windows_c_status_fieldnm)
#define status_vals (nh_cur->g_windows_c_status_vals)
#endif /* NH_CTX_FILE_WINDOWS_C_H */
