/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of wintty.c.
 * Include ONLY from wintty.c, after hack.h. */
#ifndef NH_CTX_FILE_WINTTY_C_H
#define NH_CTX_FILE_WINTTY_C_H
#define base_window (nh_cur->g_wintty_c_base_window)
#define compress_cbuf (nh_cur->g_wintty_c_compress_cbuf)
#define hpbar_color (nh_cur->g_wintty_c_hpbar_color)
#define hpbar_percent (nh_cur->g_wintty_c_hpbar_percent)
#define tty_colormasks (nh_cur->g_wintty_c_tty_colormasks)
#define tty_condition_bits (nh_cur->g_wintty_c_tty_condition_bits)
#define tty_nhgetch_nesting (nh_cur->g_wintty_c_tty_nhgetch_nesting)
#define wins (nh_cur->g_wintty_c_wins)
#define ttydisplay (nh_cur->g_wintty_c_ttydisplay)
#define morc (nh_cur->g_wintty_c_morc)
#endif /* NH_CTX_FILE_WINTTY_C_H */
