/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of worm.c.
 * Include ONLY from worm.c, after hack.h. */
#ifndef NH_CTX_FILE_WORM_C_H
#define NH_CTX_FILE_WORM_C_H
#define wheads (nh_cur->g_worm_c_wheads)
#define wtails (nh_cur->g_worm_c_wtails)
#define wgrowtime (nh_cur->g_worm_c_wgrowtime)
#endif /* NH_CTX_FILE_WORM_C_H */
