/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

/* Accessors for statics migrated out of zap.c.
 * Include ONLY from zap.c, after hack.h. */
#ifndef NH_CTX_FILE_ZAP_C_H
#define NH_CTX_FILE_ZAP_C_H
#define obj_zapped (nh_cur->g_zap_c_obj_zapped)
#define poly_zapped (nh_cur->g_zap_c_poly_zapped)
#endif /* NH_CTX_FILE_ZAP_C_H */
