/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

#ifndef NH_CTX_GEN_H
#define NH_CTX_GEN_H

#define NH_LAZY_SLOTS 8
struct nh_ctx {
    /* hot: touched every step; keep packed at the front so the
     * per-step working set spans the fewest cache lines. */
    /* --- hot --- */
    long g_moves; /* global: moves */
    long g_monstermoves; /* global: monstermoves */
    int g_multi; /* global: multi */
    boolean g_vision_full_recalc; /* global: vision_full_recalc */
    char ** g_viz_array; /* global: viz_array */
    struct sinfo g_program_state; /* global: program_state */
    int (*g_occupation)(void); /* global: occupation */
    int (*g_afternmv)(void); /* global: afternmv */
    /* --- cold --- */
    int g_track_c_utcnt; /* track.c: utcnt */
    int g_track_c_utpnt; /* track.c: utpnt */
    coord g_track_c_utrack[50]; /* track.c: utrack */
    const char * g_hname; /* global: hname */
    int g_hackpid; /* global: hackpid */
    int g_locknum; /* global: locknum */
    char g_chosen_windowtype[WINTYPELEN]; /* global: chosen_windowtype */
    int g_bases[MAXOCLASSES]; /* global: bases */
    const char * g_multi_reason; /* global: multi_reason */
    int g_nroom; /* global: nroom */
    int g_nsubroom; /* global: nsubroom */
    int g_occtime; /* global: occtime */
    int g_x_maze_max; /* global: x_maze_max */
    int g_y_maze_max; /* global: y_maze_max */
    int g_otg_temp; /* global: otg_temp */
    int g_in_doagain; /* global: in_doagain */
    struct dgn_topology g_dungeon_topology; /* global: dungeon_topology */
    struct q_score g_quest_status; /* global: quest_status */
    int g_warn_obj_cnt; /* global: warn_obj_cnt */
    int g_smeq[MAXNROFROOMS + 1]; /* global: smeq */
    int g_doorindex; /* global: doorindex */
    char * g_save_cm; /* global: save_cm */
    struct kinfo g_killer; /* global: killer */
    long g_done_money; /* global: done_money */
    const char * g_nomovemsg; /* global: nomovemsg */
    char g_plname[PL_NSIZ]; /* global: plname */
    char g_pl_character[PL_CSIZ]; /* global: pl_character */
    char g_pl_race; /* global: pl_race */
    char g_pl_fruit[PL_FSIZ]; /* global: pl_fruit */
    struct fruit * g_ffruit; /* global: ffruit */
    char g_tune[6]; /* global: tune */
    boolean g_ransacked; /* global: ransacked */
    const char * g_occtxt; /* global: occtxt */
    long g_yn_number; /* global: yn_number */
    struct linfo g_level_info[MAXLINFO]; /* global: level_info */
    schar g_tbx; /* global: tbx */
    schar g_tby; /* global: tby */
    struct multishot g_m_shot; /* global: m_shot */
    dungeon g_dungeons[MAXDUNGEON]; /* global: dungeons */
    s_level * g_sp_levchn; /* global: sp_levchn */
    stairway g_upstair; /* global: upstair */
    stairway g_dnstair; /* global: dnstair */
    stairway g_upladder; /* global: upladder */
    stairway g_dnladder; /* global: dnladder */
    stairway g_sstairs; /* global: sstairs */
    dest_area g_updest; /* global: updest */
    dest_area g_dndest; /* global: dndest */
    coord g_inv_pos; /* global: inv_pos */
    boolean g_defer_see_monsters; /* global: defer_see_monsters */
    boolean g_in_mklev; /* global: in_mklev */
    boolean g_stoned; /* global: stoned */
    boolean g_unweapon; /* global: unweapon */
    boolean g_mrg_to_wielded; /* global: mrg_to_wielded */
    boolean g_in_steed_dismounting; /* global: in_steed_dismounting */
    boolean g_has_strong_rngseed; /* global: has_strong_rngseed */
    coord g_bhitpos; /* global: bhitpos */
    coord g_doors[DOORMAX]; /* global: doors */
    struct mkroom g_rooms[(MAXNROFROOMS + 1) * 2]; /* global: rooms */
    struct mkroom * g_subrooms; /* global: subrooms */
    struct mkroom * g_upstairs_room; /* global: upstairs_room */
    struct mkroom * g_dnstairs_room; /* global: dnstairs_room */
    struct mkroom * g_sstairs_room; /* global: sstairs_room */
    dlevel_t g_level; /* global: level */
    struct trap * g_ftrap; /* global: ftrap */
    struct monst g_youmonst; /* global: youmonst */
    struct context_info g_context; /* global: context */
    struct flag g_flags; /* global: flags */
    struct instance_flags g_iflags; /* global: iflags */
    struct you g_u; /* global: u */
    time_t g_ubirthday; /* global: ubirthday */
    struct u_realtime g_urealtime; /* global: urealtime */
    schar g_lastseentyp[COLNO][ROWNO]; /* global: lastseentyp */
    struct obj * g_invent; /* global: invent */
    struct obj * g_uwep; /* global: uwep */
    struct obj * g_uarm; /* global: uarm */
    struct obj * g_uswapwep; /* global: uswapwep */
    struct obj * g_uquiver; /* global: uquiver */
    struct obj * g_uarmu; /* global: uarmu */
    struct obj * g_uskin; /* global: uskin */
    struct obj * g_uarmc; /* global: uarmc */
    struct obj * g_uarmh; /* global: uarmh */
    struct obj * g_uarms; /* global: uarms */
    struct obj * g_uarmg; /* global: uarmg */
    struct obj * g_uarmf; /* global: uarmf */
    struct obj * g_uamul; /* global: uamul */
    struct obj * g_uright; /* global: uright */
    struct obj * g_uleft; /* global: uleft */
    struct obj * g_ublindf; /* global: ublindf */
    struct obj * g_uchain; /* global: uchain */
    struct obj * g_uball; /* global: uball */
    struct obj * g_current_wand; /* global: current_wand */
    struct obj * g_thrownobj; /* global: thrownobj */
    struct obj * g_kickedobj; /* global: kickedobj */
    struct spell g_spl_book[MAXSPELL + 1]; /* global: spl_book */
    long g_wailmsg; /* global: wailmsg */
    struct obj * g_migrating_objs; /* global: migrating_objs */
    struct obj * g_billobjs; /* global: billobjs */
    char g_dogname[PL_PSIZ]; /* global: dogname */
    char g_catname[PL_PSIZ]; /* global: catname */
    char g_horsename[PL_PSIZ]; /* global: horsename */
    char g_preferred_pet; /* global: preferred_pet */
    struct monst * g_mydogs; /* global: mydogs */
    struct monst * g_migrating_mons; /* global: migrating_mons */
    struct autopickup_exception * g_apelist; /* global: apelist */
    struct mvitals g_mvitals[NUMMONS]; /* global: mvitals */
    long g_domove_attempting; /* global: domove_attempting */
    long g_domove_succeeded; /* global: domove_succeeded */
    struct menucoloring * g_menu_colorings; /* global: menu_colorings */
    winid g_WIN_MESSAGE; /* global: WIN_MESSAGE */
    winid g_WIN_STATUS; /* global: WIN_STATUS */
    winid g_WIN_MAP; /* global: WIN_MAP */
    winid g_WIN_INVEN; /* global: WIN_INVEN */
    char g_toplines[TBUFSZ]; /* global: toplines */
    struct tc_gbl_data g_tc_gbl_data; /* global: tc_gbl_data */
    char * g_fqn_prefix[PREFIX_COUNT]; /* global: fqn_prefix */
    struct savefile_info g_sfcap; /* global: sfcap */
    struct savefile_info g_sfrestinfo; /* global: sfrestinfo */
    struct savefile_info g_sfsaveinfo; /* global: sfsaveinfo */
    struct plinemsg_type * g_plinemsg_types; /* global: plinemsg_types */
    unsigned g_nhUse_dummy; /* global: nhUse_dummy */
    short g_options_c_n_menu_mapped; /* options.c: n_menu_mapped */
    char g_attrib_c_from_what_buf[256]; /* attrib.c: from_what_buf */
    /* lazily-allocated per-env blobs whose types are private to one
     * .c file (e.g. options.c boolopt copy); freed by nh_ctx_free.
     * Slot assignments are documented at the allocation sites. */
    void *nh_lazy[NH_LAZY_SLOTS];
};

/* One game per process/dl-copy for now; becomes __thread when the
 * multi-env single-library step lands (see docs/DESIGN.md §2). */
extern struct nh_ctx *nh_cur;

struct nh_ctx *nh_ctx_new(void);
void nh_ctx_free(struct nh_ctx *);
/* handwritten (src/nh_ctx_fixup.c): fields whose initial value
 * points into the ctx itself, e.g. subrooms = &rooms[N]. */
void nh_ctx_fixup(struct nh_ctx *);

/* accessors: true globals (statics get per-file headers) */
#define moves (nh_cur->g_moves)
#define monstermoves (nh_cur->g_monstermoves)
#define multi (nh_cur->g_multi)
#define vision_full_recalc (nh_cur->g_vision_full_recalc)
#define viz_array (nh_cur->g_viz_array)
#define program_state (nh_cur->g_program_state)
#define occupation (nh_cur->g_occupation)
#define afternmv (nh_cur->g_afternmv)
#define hname (nh_cur->g_hname)
#define hackpid (nh_cur->g_hackpid)
#define locknum (nh_cur->g_locknum)
#define chosen_windowtype (nh_cur->g_chosen_windowtype)
#define bases (nh_cur->g_bases)
#define multi_reason (nh_cur->g_multi_reason)
#define nroom (nh_cur->g_nroom)
#define nsubroom (nh_cur->g_nsubroom)
#define occtime (nh_cur->g_occtime)
#define x_maze_max (nh_cur->g_x_maze_max)
#define y_maze_max (nh_cur->g_y_maze_max)
#define otg_temp (nh_cur->g_otg_temp)
#define in_doagain (nh_cur->g_in_doagain)
#define dungeon_topology (nh_cur->g_dungeon_topology)
#define quest_status (nh_cur->g_quest_status)
#define warn_obj_cnt (nh_cur->g_warn_obj_cnt)
#define smeq (nh_cur->g_smeq)
#define doorindex (nh_cur->g_doorindex)
#define save_cm (nh_cur->g_save_cm)
#define killer (nh_cur->g_killer)
#define done_money (nh_cur->g_done_money)
#define nomovemsg (nh_cur->g_nomovemsg)
#define plname (nh_cur->g_plname)
#define pl_character (nh_cur->g_pl_character)
#define pl_race (nh_cur->g_pl_race)
#define pl_fruit (nh_cur->g_pl_fruit)
#define ffruit (nh_cur->g_ffruit)
#define tune (nh_cur->g_tune)
#define ransacked (nh_cur->g_ransacked)
#define occtxt (nh_cur->g_occtxt)
#define yn_number (nh_cur->g_yn_number)
#define level_info (nh_cur->g_level_info)
#define tbx (nh_cur->g_tbx)
#define tby (nh_cur->g_tby)
#define m_shot (nh_cur->g_m_shot)
#define dungeons (nh_cur->g_dungeons)
#define sp_levchn (nh_cur->g_sp_levchn)
#define upstair (nh_cur->g_upstair)
#define dnstair (nh_cur->g_dnstair)
#define upladder (nh_cur->g_upladder)
#define dnladder (nh_cur->g_dnladder)
#define sstairs (nh_cur->g_sstairs)
#define updest (nh_cur->g_updest)
#define dndest (nh_cur->g_dndest)
#define inv_pos (nh_cur->g_inv_pos)
#define defer_see_monsters (nh_cur->g_defer_see_monsters)
#define in_mklev (nh_cur->g_in_mklev)
#define stoned (nh_cur->g_stoned)
#define unweapon (nh_cur->g_unweapon)
#define mrg_to_wielded (nh_cur->g_mrg_to_wielded)
#define in_steed_dismounting (nh_cur->g_in_steed_dismounting)
#define has_strong_rngseed (nh_cur->g_has_strong_rngseed)
#define bhitpos (nh_cur->g_bhitpos)
#define doors (nh_cur->g_doors)
#define rooms (nh_cur->g_rooms)
#define subrooms (nh_cur->g_subrooms)
#define upstairs_room (nh_cur->g_upstairs_room)
#define dnstairs_room (nh_cur->g_dnstairs_room)
#define sstairs_room (nh_cur->g_sstairs_room)
#define level (nh_cur->g_level)
#define ftrap (nh_cur->g_ftrap)
#define youmonst (nh_cur->g_youmonst)
#define context (nh_cur->g_context)
#define flags (nh_cur->g_flags)
#define iflags (nh_cur->g_iflags)
#define u (nh_cur->g_u)
#define ubirthday (nh_cur->g_ubirthday)
#define urealtime (nh_cur->g_urealtime)
#define lastseentyp (nh_cur->g_lastseentyp)
#define invent (nh_cur->g_invent)
#define uwep (nh_cur->g_uwep)
#define uarm (nh_cur->g_uarm)
#define uswapwep (nh_cur->g_uswapwep)
#define uquiver (nh_cur->g_uquiver)
#define uarmu (nh_cur->g_uarmu)
#define uskin (nh_cur->g_uskin)
#define uarmc (nh_cur->g_uarmc)
#define uarmh (nh_cur->g_uarmh)
#define uarms (nh_cur->g_uarms)
#define uarmg (nh_cur->g_uarmg)
#define uarmf (nh_cur->g_uarmf)
#define uamul (nh_cur->g_uamul)
#define uright (nh_cur->g_uright)
#define uleft (nh_cur->g_uleft)
#define ublindf (nh_cur->g_ublindf)
#define uchain (nh_cur->g_uchain)
#define uball (nh_cur->g_uball)
#define current_wand (nh_cur->g_current_wand)
#define thrownobj (nh_cur->g_thrownobj)
#define kickedobj (nh_cur->g_kickedobj)
#define spl_book (nh_cur->g_spl_book)
#define wailmsg (nh_cur->g_wailmsg)
#define migrating_objs (nh_cur->g_migrating_objs)
#define billobjs (nh_cur->g_billobjs)
#define dogname (nh_cur->g_dogname)
#define catname (nh_cur->g_catname)
#define horsename (nh_cur->g_horsename)
#define preferred_pet (nh_cur->g_preferred_pet)
#define mydogs (nh_cur->g_mydogs)
#define migrating_mons (nh_cur->g_migrating_mons)
#define apelist (nh_cur->g_apelist)
#define mvitals (nh_cur->g_mvitals)
#define domove_attempting (nh_cur->g_domove_attempting)
#define domove_succeeded (nh_cur->g_domove_succeeded)
#define menu_colorings (nh_cur->g_menu_colorings)
#define WIN_MESSAGE (nh_cur->g_WIN_MESSAGE)
#define WIN_STATUS (nh_cur->g_WIN_STATUS)
#define WIN_MAP (nh_cur->g_WIN_MAP)
#define WIN_INVEN (nh_cur->g_WIN_INVEN)
#define toplines (nh_cur->g_toplines)
#define tc_gbl_data (nh_cur->g_tc_gbl_data)
#define fqn_prefix (nh_cur->g_fqn_prefix)
#define sfcap (nh_cur->g_sfcap)
#define sfrestinfo (nh_cur->g_sfrestinfo)
#define sfsaveinfo (nh_cur->g_sfsaveinfo)
#define plinemsg_types (nh_cur->g_plinemsg_types)
#define nhUse_dummy (nh_cur->g_nhUse_dummy)

#endif /* NH_CTX_GEN_H */
