/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

#ifndef NH_CTX_GEN_H
#define NH_CTX_GEN_H

#define NH_LAZY_SLOTS 64
struct nh_ctx {
    /* hot: touched every step; keep packed at the front so the
     * per-step working set spans the fewest cache lines. */
    /* --- hot --- */
    long g_moves; /* global: moves */
    long g_monstermoves; /* global: monstermoves */
    int g_multi; /* global: multi */
    boolean g_vision_full_recalc; /* global: vision_full_recalc */
    char ** g_viz_array; /* global: viz_array */
    struct sinfo g_program_state; /* global: program_state */
    int (*g_occupation)(void); /* global: occupation */
    int (*g_afternmv)(void); /* global: afternmv */
    char g_vision_c_could_see[2][ROWNO][COLNO]; /* vision.c: could_see */
    char g_vision_c_viz_clear[ROWNO][COLNO]; /* vision.c: viz_clear */
    char g_vision_c_left_ptrs[ROWNO][COLNO]; /* vision.c: left_ptrs */
    char g_vision_c_right_ptrs[ROWNO][COLNO]; /* vision.c: right_ptrs */
    char * g_vision_c_viz_clear_rows[ROWNO]; /* vision.c: viz_clear_rows */
    char * g_vision_c_cs_rows0[ROWNO]; /* vision.c: cs_rows0 */
    char * g_vision_c_cs_rows1[ROWNO]; /* vision.c: cs_rows1 */
    char g_vision_c_cs_rmin0[ROWNO]; /* vision.c: cs_rmin0 */
    char g_vision_c_cs_rmax0[ROWNO]; /* vision.c: cs_rmax0 */
    char g_vision_c_cs_rmin1[ROWNO]; /* vision.c: cs_rmin1 */
    char g_vision_c_cs_rmax1[ROWNO]; /* vision.c: cs_rmax1 */
    char * g_vision_c_viz_rmin; /* vision.c: viz_rmin */
    char * g_vision_c_viz_rmax; /* vision.c: viz_rmax */
    char g_display_c_gbuf_start[ROWNO]; /* display.c: gbuf_start */
    char g_display_c_gbuf_stop[ROWNO]; /* display.c: gbuf_stop */
    int g_xwaitingforspace; /* global: xwaitingforspace */
    isaac64_ctx g_rnd_c_rng_state[2]; /* rnd.c: rng_state */
    int g_rnd_c_rng_init[2]; /* rnd.c: rng_init */
    nhsym g_drawing_c_showsyms[SYM_MAX]; /* drawing.c: showsyms */
    /* --- cold --- */
    int g_track_c_utcnt; /* track.c: utcnt */
    int g_track_c_utpnt; /* track.c: utpnt */
    coord g_track_c_utrack[50]; /* track.c: utrack */
    const char * g_hname; /* global: hname */
    int g_hackpid; /* global: hackpid */
    int g_locknum; /* global: locknum */
    char g_chosen_windowtype[WINTYPELEN]; /* global: chosen_windowtype */
    int g_bases[MAXOCLASSES]; /* global: bases */
    const char * g_multi_reason; /* global: multi_reason */
    int g_nroom; /* global: nroom */
    int g_nsubroom; /* global: nsubroom */
    int g_occtime; /* global: occtime */
    int g_x_maze_max; /* global: x_maze_max */
    int g_y_maze_max; /* global: y_maze_max */
    int g_otg_temp; /* global: otg_temp */
    int g_in_doagain; /* global: in_doagain */
    struct dgn_topology g_dungeon_topology; /* global: dungeon_topology */
    struct q_score g_quest_status; /* global: quest_status */
    int g_warn_obj_cnt; /* global: warn_obj_cnt */
    int g_smeq[MAXNROFROOMS + 1]; /* global: smeq */
    int g_doorindex; /* global: doorindex */
    char * g_save_cm; /* global: save_cm */
    struct kinfo g_killer; /* global: killer */
    long g_done_money; /* global: done_money */
    const char * g_nomovemsg; /* global: nomovemsg */
    char g_plname[PL_NSIZ]; /* global: plname */
    char g_pl_character[PL_CSIZ]; /* global: pl_character */
    char g_pl_race; /* global: pl_race */
    char g_pl_fruit[PL_FSIZ]; /* global: pl_fruit */
    struct fruit * g_ffruit; /* global: ffruit */
    char g_tune[6]; /* global: tune */
    boolean g_ransacked; /* global: ransacked */
    const char * g_occtxt; /* global: occtxt */
    long g_yn_number; /* global: yn_number */
    struct linfo g_level_info[MAXLINFO]; /* global: level_info */
    schar g_tbx; /* global: tbx */
    schar g_tby; /* global: tby */
    struct multishot g_m_shot; /* global: m_shot */
    dungeon g_dungeons[MAXDUNGEON]; /* global: dungeons */
    s_level * g_sp_levchn; /* global: sp_levchn */
    stairway g_upstair; /* global: upstair */
    stairway g_dnstair; /* global: dnstair */
    stairway g_upladder; /* global: upladder */
    stairway g_dnladder; /* global: dnladder */
    stairway g_sstairs; /* global: sstairs */
    dest_area g_updest; /* global: updest */
    dest_area g_dndest; /* global: dndest */
    coord g_inv_pos; /* global: inv_pos */
    boolean g_defer_see_monsters; /* global: defer_see_monsters */
    boolean g_in_mklev; /* global: in_mklev */
    boolean g_stoned; /* global: stoned */
    boolean g_unweapon; /* global: unweapon */
    boolean g_mrg_to_wielded; /* global: mrg_to_wielded */
    boolean g_in_steed_dismounting; /* global: in_steed_dismounting */
    boolean g_has_strong_rngseed; /* global: has_strong_rngseed */
    coord g_bhitpos; /* global: bhitpos */
    coord g_doors[DOORMAX]; /* global: doors */
    struct mkroom g_rooms[(MAXNROFROOMS + 1) * 2]; /* global: rooms */
    struct mkroom * g_subrooms; /* global: subrooms */
    struct mkroom * g_upstairs_room; /* global: upstairs_room */
    struct mkroom * g_dnstairs_room; /* global: dnstairs_room */
    struct mkroom * g_sstairs_room; /* global: sstairs_room */
    dlevel_t g_level; /* global: level */
    struct trap * g_ftrap; /* global: ftrap */
    struct monst g_youmonst; /* global: youmonst */
    struct context_info g_context; /* global: context */
    struct flag g_flags; /* global: flags */
    struct instance_flags g_iflags; /* global: iflags */
    struct you g_u; /* global: u */
    time_t g_ubirthday; /* global: ubirthday */
    struct u_realtime g_urealtime; /* global: urealtime */
    schar g_lastseentyp[COLNO][ROWNO]; /* global: lastseentyp */
    struct obj * g_invent; /* global: invent */
    struct obj * g_uwep; /* global: uwep */
    struct obj * g_uarm; /* global: uarm */
    struct obj * g_uswapwep; /* global: uswapwep */
    struct obj * g_uquiver; /* global: uquiver */
    struct obj * g_uarmu; /* global: uarmu */
    struct obj * g_uskin; /* global: uskin */
    struct obj * g_uarmc; /* global: uarmc */
    struct obj * g_uarmh; /* global: uarmh */
    struct obj * g_uarms; /* global: uarms */
    struct obj * g_uarmg; /* global: uarmg */
    struct obj * g_uarmf; /* global: uarmf */
    struct obj * g_uamul; /* global: uamul */
    struct obj * g_uright; /* global: uright */
    struct obj * g_uleft; /* global: uleft */
    struct obj * g_ublindf; /* global: ublindf */
    struct obj * g_uchain; /* global: uchain */
    struct obj * g_uball; /* global: uball */
    struct obj * g_current_wand; /* global: current_wand */
    struct obj * g_thrownobj; /* global: thrownobj */
    struct obj * g_kickedobj; /* global: kickedobj */
    struct spell g_spl_book[MAXSPELL + 1]; /* global: spl_book */
    long g_wailmsg; /* global: wailmsg */
    struct obj * g_migrating_objs; /* global: migrating_objs */
    struct obj * g_billobjs; /* global: billobjs */
    char g_dogname[PL_PSIZ]; /* global: dogname */
    char g_catname[PL_PSIZ]; /* global: catname */
    char g_horsename[PL_PSIZ]; /* global: horsename */
    char g_preferred_pet; /* global: preferred_pet */
    struct monst * g_mydogs; /* global: mydogs */
    struct monst * g_migrating_mons; /* global: migrating_mons */
    struct autopickup_exception * g_apelist; /* global: apelist */
    struct mvitals g_mvitals[NUMMONS]; /* global: mvitals */
    long g_domove_attempting; /* global: domove_attempting */
    long g_domove_succeeded; /* global: domove_succeeded */
    struct menucoloring * g_menu_colorings; /* global: menu_colorings */
    winid g_WIN_MESSAGE; /* global: WIN_MESSAGE */
    winid g_WIN_STATUS; /* global: WIN_STATUS */
    winid g_WIN_MAP; /* global: WIN_MAP */
    winid g_WIN_INVEN; /* global: WIN_INVEN */
    char g_toplines[TBUFSZ]; /* global: toplines */
    struct tc_gbl_data g_tc_gbl_data; /* global: tc_gbl_data */
    char * g_fqn_prefix[PREFIX_COUNT]; /* global: fqn_prefix */
    struct savefile_info g_sfcap; /* global: sfcap */
    struct savefile_info g_sfrestinfo; /* global: sfrestinfo */
    struct savefile_info g_sfsaveinfo; /* global: sfsaveinfo */
    struct plinemsg_type * g_plinemsg_types; /* global: plinemsg_types */
    unsigned g_nhUse_dummy; /* global: nhUse_dummy */
    short g_options_c_n_menu_mapped; /* options.c: n_menu_mapped */
    char g_attrib_c_from_what_buf[256]; /* attrib.c: from_what_buf */
    struct cmd g_Cmd; /* global: Cmd */
    int g_cmd_c_alt_esc; /* cmd.c: alt_esc */
    int (*g_cmd_c_timed_occ_fn)(void); /* cmd.c: timed_occ_fn */
    char g_cmd_c_pushq[20]; /* cmd.c: pushq */
    char g_cmd_c_saveq[20]; /* cmd.c: saveq */
    int g_cmd_c_phead; /* cmd.c: phead */
    int g_cmd_c_ptail; /* cmd.c: ptail */
    int g_cmd_c_shead; /* cmd.c: shead */
    int g_cmd_c_stail; /* cmd.c: stail */
    short g_cmd_c_en_win; /* cmd.c: en_win */
    boolean g_cmd_c_en_via_menu; /* cmd.c: en_via_menu */
    const char * g_cmd_c_readchar_queue; /* cmd.c: readchar_queue */
    int g_vision_c_vis_start_row; /* vision.c: vis_start_row */
    int g_vision_c_vis_start_col; /* vision.c: vis_start_col */
    int g_vision_c_vis_step; /* vision.c: vis_step */
    char ** g_vision_c_vis_cs_rows; /* vision.c: vis_cs_rows */
    char * g_vision_c_vis_cs_left; /* vision.c: vis_cs_left */
    char * g_vision_c_vis_cs_right; /* vision.c: vis_cs_right */
    void (*g_vision_c_vis_func)(); /* vision.c: vis_func */
    void * g_vision_c_vis_varg; /* vision.c: vis_varg */
    int g_vision_c_vision_recur_depth; /* vision.c: vision_recur_depth */
    unsigned char g_vision_c_vision_colbump[COLNO + 1]; /* vision.c: vision_colbump */
    char g_botl_c_strength_buf[32]; /* botl.c: strength_buf */
    boolean g_botl_c_blinit; /* botl.c: blinit */
    boolean g_botl_c_update_all; /* botl.c: update_all */
    boolean g_botl_c_valset[23]; /* botl.c: valset */
    long g_botl_c_bl_hilite_moves; /* botl.c: bl_hilite_moves */
    unsigned long g_botl_c_cond_hilites[21]; /* botl.c: cond_hilites */
    int g_botl_c_now_or_before_idx; /* botl.c: now_or_before_idx */
    int g_botl_c_status_hilite_str_id; /* botl.c: status_hilite_str_id */
    char g_botl_c_blstats_initalready; /* botl.c: blstats_initalready */
    void * g_botl_c_status_hilite_str_p; /* botl.c: status_hilite_str_p */
    int g_sp_lev_c_min_rx; /* sp_lev.c: min_rx */
    int g_sp_lev_c_max_rx; /* sp_lev.c: max_rx */
    int g_sp_lev_c_min_ry; /* sp_lev.c: min_ry */
    int g_sp_lev_c_max_ry; /* sp_lev.c: max_ry */
    char g_sp_lev_c_splev_map[COLNO][ROWNO]; /* sp_lev.c: splev_map */
    schar g_sp_lev_c_xstart; /* sp_lev.c: xstart */
    schar g_sp_lev_c_ystart; /* sp_lev.c: ystart */
    char g_sp_lev_c_xsize; /* sp_lev.c: xsize */
    char g_sp_lev_c_ysize; /* sp_lev.c: ysize */
    char * g_sp_lev_c_lev_message; /* sp_lev.c: lev_message */
    void * g_sp_lev_c_lregions_p; /* sp_lev.c: lregions_p */
    int g_sp_lev_c_num_lregions; /* sp_lev.c: num_lregions */
    boolean g_sp_lev_c_splev_init_present; /* sp_lev.c: splev_init_present */
    boolean g_sp_lev_c_icedpools; /* sp_lev.c: icedpools */
    int g_sp_lev_c_container_idx; /* sp_lev.c: container_idx */
    struct obj * g_sp_lev_c_container_obj[10]; /* sp_lev.c: container_obj */
    struct monst * g_sp_lev_c_invent_carrying_monster; /* sp_lev.c: invent_carrying_monster */
    int g_sp_lev_c_mines_prize_count; /* sp_lev.c: mines_prize_count */
    int g_sp_lev_c_soko_prize_count; /* sp_lev.c: soko_prize_count */
    schar g_sp_lev_c_floodfillchk_match_under_typ; /* sp_lev.c: floodfillchk_match_under_typ */
    void * g_mkmaze_c_bbubbles; /* mkmaze.c: bbubbles */
    void * g_mkmaze_c_ebubbles; /* mkmaze.c: ebubbles */
    boolean g_mkmaze_c_movebubbles_up; /* mkmaze.c: movebubbles_up */
    int g_mkmaze_c_water_xmin; /* mkmaze.c: water_xmin */
    int g_mkmaze_c_water_ymin; /* mkmaze.c: water_ymin */
    int g_mkmaze_c_water_xmax; /* mkmaze.c: water_xmax */
    int g_mkmaze_c_water_ymax; /* mkmaze.c: water_ymax */
    struct trap * g_mkmaze_c_wportal; /* mkmaze.c: wportal */
    int g_display_c_bad_count[36]; /* display.c: bad_count */
    void * g_display_c_tglyph_p; /* display.c: tglyph_p */
    boolean g_display_c_in_cls; /* display.c: in_cls */
    int g_display_c_flushing; /* display.c: flushing */
    int g_display_c_delay_flushing; /* display.c: delay_flushing */
    schar g_display_c_swallowed_lastx; /* display.c: swallowed_lastx */
    schar g_display_c_swallowed_lasty; /* display.c: swallowed_lasty */
    schar g_display_c_under_water_lastx; /* display.c: under_water_lastx */
    schar g_display_c_under_water_lasty; /* display.c: under_water_lasty */
    boolean g_display_c_under_water_dela; /* display.c: under_water_dela */
    boolean g_display_c_under_ground_dela; /* display.c: under_ground_dela */
    int g_display_c_nul_gbuf_new; /* display.c: nul_gbuf_new */
    int g_display_c_nul_gbuf_glyph; /* display.c: nul_gbuf_glyph */
    int g_invent_c_lastinvnr; /* invent.c: lastinvnr */
    unsigned g_invent_c_sortlootmode; /* invent.c: sortlootmode */
    int g_invent_c_cached_pickinv_win; /* invent.c: cached_pickinv_win */
    int g_invent_c_this_type; /* invent.c: this_type */
    unsigned g_invent_c_invbufsiz; /* invent.c: invbufsiz */
    schar g_invent_c_only_x; /* invent.c: only_x */
    schar g_invent_c_only_y; /* invent.c: only_y */
    char g_invent_c_safeq_xprn_let; /* invent.c: safeq_xprn_let */
    boolean g_invent_c_safeq_xprn_dot; /* invent.c: safeq_xprn_dot */
    char g_invent_c_armcat[8]; /* invent.c: armcat */
    char g_invent_c_li[256]; /* invent.c: li */
    char g_invent_c_altbuf[256]; /* invent.c: altbuf */
    void * g_windows_c_last_winchoice; /* windows.c: last_winchoice */
    boolean g_windows_c_status_activefields[23]; /* windows.c: status_activefields */
    const char * g_windows_c_status_fieldfmt[23]; /* windows.c: status_fieldfmt */
    const char * g_windows_c_status_fieldnm[23]; /* windows.c: status_fieldnm */
    char * g_windows_c_status_vals[23]; /* windows.c: status_vals */
    int g_wintty_c_base_window; /* wintty.c: base_window */
    char g_wintty_c_compress_cbuf[256]; /* wintty.c: compress_cbuf */
    int g_wintty_c_hpbar_color; /* wintty.c: hpbar_color */
    int g_wintty_c_hpbar_percent; /* wintty.c: hpbar_percent */
    unsigned long * g_wintty_c_tty_colormasks; /* wintty.c: tty_colormasks */
    long g_wintty_c_tty_condition_bits; /* wintty.c: tty_condition_bits */
    int g_wintty_c_tty_nhgetch_nesting; /* wintty.c: tty_nhgetch_nesting */
    boolean g_topl_c_initd; /* topl.c: initd */
    int g_topl_c_nxtidx; /* topl.c: nxtidx */
    boolean g_getline_c_suppress_history; /* getline.c: suppress_history */
    struct WinDesc * g_wintty_c_wins[20]; /* wintty.c: wins */
    struct DisplayDesc * g_wintty_c_ttydisplay; /* wintty.c: ttydisplay */
    char g_wintty_c_morc; /* wintty.c: morc */
    char g_files_c_savef[45]; /* files.c: savef */
    char g_files_c_bones[16]; /* files.c: bones */
    char * g_files_c_config_section_chosen; /* files.c: config_section_chosen */
    char * g_files_c_config_section_current; /* files.c: config_section_current */
    char g_files_c_fqn_fname[2048]; /* files.c: fqn_fname */
    int g_files_c_lockptr; /* files.c: lockptr */
    char g_files_c_wizkit[128]; /* files.c: wizkit */
    int g_dungeon_c_n_dgns; /* dungeon.c: n_dgns */
    long g_shk_c_pickmovetime; /* shk.c: pickmovetime */
    char g_shk_c_empty_shops[5]; /* shk.c: empty_shops */
    boolean g_muse_c_m_using; /* muse.c: m_using */
    int g_muse_c_trapx; /* muse.c: trapx */
    int g_muse_c_trapy; /* muse.c: trapy */
    boolean g_muse_c_zap_oseen; /* muse.c: zap_oseen */
    boolean g_pickup_c_abort_looting; /* pickup.c: abort_looting */
    boolean g_pickup_c_autopick_costly; /* pickup.c: autopick_costly */
    boolean g_pickup_c_bucx_filter; /* pickup.c: bucx_filter */
    boolean g_pickup_c_class_filter; /* pickup.c: class_filter */
    struct obj * g_pickup_c_current_container; /* pickup.c: current_container */
    int g_pickup_c_encumber_msg_oldcap; /* pickup.c: encumber_msg_oldcap */
    boolean g_pickup_c_shop_filter; /* pickup.c: shop_filter */
    long g_pickup_c_val_for_n_or_more; /* pickup.c: val_for_n_or_more */
    char g_pickup_c_valid_menu_classes[24]; /* pickup.c: valid_menu_classes */
    int g_pickup_c_vmc_count; /* pickup.c: vmc_count */
    int g_hack_c_domove_skates; /* hack.c: domove_skates */
    char g_hack_c_in_rooms_buf[5]; /* hack.c: in_rooms_buf */
    int g_hack_c_inspoteffects; /* hack.c: inspoteffects */
    long g_hack_c_moverock_lastmovetime; /* hack.c: moverock_lastmovetime */
    schar g_hack_c_spotloc_x; /* hack.c: spotloc_x */
    schar g_hack_c_spotloc_y; /* hack.c: spotloc_y */
    int g_hack_c_spotterrain; /* hack.c: spotterrain */
    struct trap * g_hack_c_spottrap; /* hack.c: spottrap */
    unsigned g_hack_c_spottraptyp; /* hack.c: spottraptyp */
    void * g_hack_c_tmp_anything_p; /* hack.c: tmp_anything_p */
    int g_hack_c_wc; /* hack.c: wc */
    char g_do_name_c_dxdy_buf[30]; /* do_name.c: dxdy_buf */
    char g_do_name_c_rndmonnam_buf[256]; /* do_name.c: rndmonnam_buf */
    int g_do_name_c_gloc_filter_match_glyph; /* do_name.c: gloc_filter_match_glyph */
    void * g_do_name_c_gloc_filter_map_p; /* do_name.c: gloc_filter_map_p */
    int g_do_name_c_mbuf_idx; /* do_name.c: mbuf_idx */
    char g_do_name_c_mbufs[5 * 256]; /* do_name.c: mbufs */
    int g_do_name_c_via_naming; /* do_name.c: via_naming */
    char g_trap_c_tnbuf[12]; /* trap.c: tnbuf */
    int g_trap_c_force_mintrap; /* trap.c: force_mintrap */
    boolean g_trap_c_recursive_mine; /* trap.c: recursive_mine */
    int g_drawing_c_currentgraphics; /* drawing.c: currentgraphics */
    char g_files_c_lock[46]; /* files.c: lock */
    boolean g_restoring; /* global: restoring */
    boolean g_notonhead; /* global: notonhead */
    unsigned long g_nle_seeds[3]; /* global: nle_seeds */
    int g_rumors_c_oracle_flg; /* rumors.c: oracle_flg */
    unsigned g_rumors_c_oracle_cnt; /* rumors.c: oracle_cnt */
    long g_rumors_c_true_rumor_size; /* rumors.c: true_rumor_size */
    schar g_artifact_c_artidisco[33]; /* artifact.c: artidisco */
    boolean g_artifact_c_artiexist[35]; /* artifact.c: artiexist */
    int g_artifact_c_nesting; /* artifact.c: nesting */
    char g_artifact_c_resbuf[20]; /* artifact.c: resbuf */
    int g_artifact_c_mkot_trap_warn_count; /* artifact.c: mkot_trap_warn_count */
    int g_artifact_c_spec_dbon_applies; /* artifact.c: spec_dbon_applies */
    boolean g_artifact_c_touch_blasted; /* artifact.c: touch_blasted */
    int g_apply_c_jumping_is_magic; /* apply.c: jumping_is_magic */
    int g_apply_c_polearm_range_max; /* apply.c: polearm_range_max */
    int g_apply_c_polearm_range_min; /* apply.c: polearm_range_min */
    void * g_save_c_bw_file; /* save.c: bw_file */
    int g_save_c_bwritefd; /* save.c: bwritefd */
    boolean g_save_c_compressing; /* save.c: compressing */
    int g_save_c_count_only; /* save.c: count_only */
    unsigned char g_save_c_outbuf[256]; /* save.c: outbuf */
    unsigned short g_save_c_outbufp; /* save.c: outbufp */
    short g_save_c_outrunlength; /* save.c: outrunlength */
    const char * g_save_c_procs_name; /* save.c: procs_name */
    void (*g_save_c_procs_bclose)(int); /* save.c: procs_bclose */
    void (*g_save_c_procs_bflush)(int); /* save.c: procs_bflush */
    void (*g_save_c_procs_bufoff)(int); /* save.c: procs_bufoff */
    void (*g_save_c_procs_bufon)(int); /* save.c: procs_bufon */
    void (*g_save_c_procs_bwrite)(int, void *, unsigned int); /* save.c: procs_bwrite */
    unsigned g_save_c_usteed_id; /* save.c: usteed_id */
    unsigned g_save_c_ustuck_id; /* save.c: ustuck_id */
    char g_role_c_pa[4]; /* role.c: pa */
    int g_role_c_post_attribs; /* role.c: post_attribs */
    void * g_lock_c_xlock_door_p; /* lock.c: xlock_door_p */
    void * g_restore_c_id_map_p; /* restore.c: id_map_p */
    int g_restore_c_n_ids_mapped; /* restore.c: n_ids_mapped */
    struct fruit * g_restore_c_oldfruit; /* restore.c: oldfruit */
    long g_restore_c_omoves; /* restore.c: omoves */
    int g_restore_c_procs_mread_flags; /* restore.c: procs_mread_flags */
    const char * g_restore_c_procs_name; /* restore.c: procs_name */
    void (*g_restore_c_procs_bclose)(int); /* restore.c: procs_bclose */
    void (*g_restore_c_procs_minit)(void); /* restore.c: procs_minit */
    void (*g_restore_c_procs_mread)(int, void *, unsigned int); /* restore.c: procs_mread */
    unsigned char g_restore_c_zc_inbuf[256]; /* restore.c: zc_inbuf */
    short g_restore_c_zc_inrunlength; /* restore.c: zc_inrunlength */
    int g_restore_c_zc_mreadfd; /* restore.c: zc_mreadfd */
    char g_hacklib_c_ing_suffix_buf[256]; /* hacklib.c: ing_suffix_buf */
    char g_hacklib_c_datestr[15]; /* hacklib.c: datestr */
    int g_hacklib_c_visctrl_nbuf; /* hacklib.c: visctrl_nbuf */
    char g_hacklib_c_visctrl_bufs[5][5]; /* hacklib.c: visctrl_bufs */
    struct Role g_role_c_urole_store; /* role.c: urole_store */
    struct Race g_role_c_urace_store; /* role.c: urace_store */
    boolean g_eat_c_force_save_hs; /* eat.c: force_save_hs */
    char g_eat_c_msgbuf[256]; /* eat.c: msgbuf */
    long g_eat_c_ate_brains; /* eat.c: ate_brains */
    unsigned g_eat_c_newuhs_save_hs; /* eat.c: newuhs_save_hs */
    boolean g_eat_c_newuhs_saved_hs; /* eat.c: newuhs_saved_hs */
    int g_potion_c_nothing; /* potion.c: nothing */
    int g_potion_c_unkn; /* potion.c: unkn */
    char g_do_c_at_ladder; /* do.c: at_ladder */
    char * g_do_c_dfr_post_msg; /* do.c: dfr_post_msg */
    char * g_do_c_dfr_pre_msg; /* do.c: dfr_pre_msg */
    char g_do_c_dowipe_buf[39]; /* do.c: dowipe_buf */
    d_level g_do_c_save_dlevel_store; /* do.c: save_dlevel_store */
    char g_questpgr_c_cvt_buf[64]; /* questpgr.c: cvt_buf */
    char g_questpgr_c_nambuf[64]; /* questpgr.c: nambuf */
    void * g_questpgr_c_msg_file_p; /* questpgr.c: msg_file_p */
    unsigned g_pline_c_pline_flags; /* pline.c: pline_flags */
    int g_pline_c_in_pline; /* pline.c: in_pline */
    char g_pline_c_prevmsg[256]; /* pline.c: prevmsg */
    int g_mon_c_animal_list_count; /* mon.c: animal_list_count */
    boolean g_mon_c_disintegested; /* mon.c: disintegested */
    long g_mon_c_elemental_clog_msgmv; /* mon.c: elemental_clog_msgmv */
    boolean g_mon_c_vamp_rise_msg; /* mon.c: vamp_rise_msg */
    int g_mhitm_c_dieroll; /* mhitm.c: dieroll */
    boolean g_mhitm_c_far_noise; /* mhitm.c: far_noise */
    struct obj * g_mhitm_c_otmp; /* mhitm.c: otmp */
    long g_mhitm_c_noisetime; /* mhitm.c: noisetime */
    boolean g_mhitm_c_vis; /* mhitm.c: vis */
    int g_spell_c_sortmode; /* spell.c: sortmode */
    void * g_makemon_c_align_shift_lev_p; /* makemon.c: align_shift_lev_p */
    long g_makemon_c_align_shift_oldmoves; /* makemon.c: align_shift_oldmoves */
    int g_end_c_vanq_sortmode; /* end.c: vanq_sortmode */
    unsigned g_rnd_c_rn2disprng_seed; /* rnd.c: rn2disprng_seed */
    isaac64_ctx g_nlernd_c_lgen_base; /* nlernd.c: lgen_base */
    isaac64_ctx g_nlernd_c_lgen_state[8]; /* nlernd.c: lgen_state */
    isaac64_ctx g_nlernd_c_core_state; /* nlernd.c: core_state */
    int g_nlernd_c_lgen_initialised; /* nlernd.c: lgen_initialised */
    int g_nlernd_c_lgen_active; /* nlernd.c: lgen_active */
    struct engr * g_engrave_c_head_engr; /* engrave.c: head_engr */
    void * g_light_c_light_base; /* light.c: light_base */
    void * g_timeout_c_timer_base; /* timeout.c: timer_base */
    unsigned long g_timeout_c_timer_id; /* timeout.c: timer_id */
    void * g_region_c_regions_p; /* region.c: regions_p */
    int g_region_c_n_regions; /* region.c: n_regions */
    int g_region_c_max_regions; /* region.c: max_regions */
    struct wseg * g_worm_c_wheads[32]; /* worm.c: wheads */
    struct wseg * g_worm_c_wtails[32]; /* worm.c: wtails */
    long g_worm_c_wgrowtime[32]; /* worm.c: wgrowtime */
    void * g_dungeon_c_branches_p; /* dungeon.c: branches_p */
    int g_dungeon_c_branch_id_ctr; /* dungeon.c: branch_id_ctr */
    void * g_dungeon_c_mapseenchn_p; /* dungeon.c: mapseenchn_p */
    char g_mklev_c_made_branch; /* mklev.c: made_branch */
    schar g_mklev_c_vault_x; /* mklev.c: vault_x */
    schar g_mklev_c_vault_y; /* mklev.c: vault_y */
    int g_rect_c_rect_cnt; /* rect.c: rect_cnt */
    schar g_dogmove_c_gtyp; /* dogmove.c: gtyp */
    schar g_dogmove_c_gx; /* dogmove.c: gx */
    schar g_dogmove_c_gy; /* dogmove.c: gy */
    int g_mthrowu_c_mesg_given; /* mthrowu.c: mesg_given */
    struct monst * g_mthrowu_c_archer; /* mthrowu.c: archer */
    struct monst * g_mthrowu_c_target; /* mthrowu.c: target */
    int g_mhitu_c_dieroll; /* mhitu.c: dieroll */
    struct obj * g_mhitu_c_mon_currwep; /* mhitu.c: mon_currwep */
    struct symsetentry g_drawing_c_symset_store[2]; /* drawing.c: symset_store */
    nhsym g_drawing_c_primary_syms[SYM_MAX]; /* drawing.c: primary_syms */
    nhsym g_drawing_c_rogue_syms[SYM_MAX]; /* drawing.c: rogue_syms */
    nhsym g_drawing_c_ov_primary_syms[SYM_MAX]; /* drawing.c: ov_primary_syms */
    nhsym g_drawing_c_ov_rogue_syms[SYM_MAX]; /* drawing.c: ov_rogue_syms */
    nhsym g_drawing_c_warnsyms[6]; /* drawing.c: warnsyms */
    int g_mkmap_c_n_loc_filled; /* mkmap.c: n_loc_filled */
    unsigned g_steal_c_stealmid; /* steal.c: stealmid */
    unsigned g_steal_c_stealoid; /* steal.c: stealoid */
    struct obj * g_weapon_c_propellor; /* weapon.c: propellor */
    schar g_pray_c_p_aligntyp; /* pray.c: p_aligntyp */
    int g_pray_c_p_trouble; /* pray.c: p_trouble */
    int g_pray_c_p_type; /* pray.c: p_type */
    boolean g_zap_c_obj_zapped; /* zap.c: obj_zapped */
    int g_zap_c_poly_zapped; /* zap.c: poly_zapped */
    boolean g_uhitm_c_cleave_clockwise; /* uhitm.c: cleave_clockwise */
    char g_uhitm_c_msgbuf[256]; /* uhitm.c: msgbuf */
    struct obj * g_teleport_c_telescroll; /* teleport.c: telescroll */
    int g_polyself_c_sex_change_ok; /* polyself.c: sex_change_ok */
    void * g_read_c_gremlins_p; /* read.c: gremlins_p */
    boolean g_read_c_known; /* read.c: known */
    void * g_ball_c_bcp_p; /* ball.c: bcp_p */
    void * g_ball_c_bcu_p; /* ball.c: bcu_p */
    int g_ball_c_bcrestriction; /* ball.c: bcrestriction */
    boolean g_dig_c_did_dig_msg; /* dig.c: did_dig_msg */
    char g_dbridge_c_wholebuf[80]; /* dbridge.c: wholebuf */
    void * g_dbridge_c_occupants_p; /* dbridge.c: occupants_p */
    char g_do_wear_c_offdelaybuf[60]; /* do_wear.c: offdelaybuf */
    boolean g_do_wear_c_initial_don; /* do_wear.c: initial_don */
    int g_dog_c_petname_used; /* dog.c: petname_used */
    short g_o_init_c_disco[NUM_OBJECTS]; /* o_init.c: disco */
    char g_objnam_c_obufs[12][256]; /* objnam.c: obufs */
    long g_topten_c_final_fpos; /* topten.c: final_fpos */
    void * g_topten_c_tt_buf_p; /* topten.c: tt_buf_p */
    int g_topten_c_toptenwin; /* topten.c: toptenwin */
    void * g_topten_c_tt_head_p; /* topten.c: tt_head_p */
    void * g_extralev_c_r_p; /* extralev.c: r_p */
    char g_mapglyph_c_encbuf[20]; /* mapglyph.c: encbuf */
    char g_mkobj_c_unknown[32]; /* mkobj.c: unknown */
    char g_priest_c_piousness_buf[32]; /* priest.c: piousness_buf */
    long g_dothrow_c_breakobj_lastmovetime; /* dothrow.c: breakobj_lastmovetime */
    boolean g_dothrow_c_breakobj_peaceful_shk; /* dothrow.c: breakobj_peaceful_shk */
    const char * g_options_c_opt_intro[10]; /* options.c: opt_intro */
    char g_options_c_fmtstr_doset[24]; /* options.c: fmtstr_doset */
    boolean g_options_c_made_fmtstr; /* options.c: made_fmtstr */
    struct symsetentry * g_symset_list; /* global: symset_list */
    aligntyp g_sp_lev_c_ralign[3]; /* sp_lev.c: ralign */
    char g_cmd_c_travelcmd[2]; /* cmd.c: travelcmd */
    char g_hacklib_c_s_suffix_buf[256]; /* hacklib.c: s_suffix_buf */
    char g_hacklib_c_sitoa_buf[13]; /* hacklib.c: sitoa_buf */
    coord g_mkroom_c_shrine_buf; /* mkroom.c: shrine_buf */
    char g_options_c_mapped_menu_cmds[33]; /* options.c: mapped_menu_cmds */
    boolean g_files_c_chosen_symset_start; /* files.c: chosen_symset_start */
    boolean g_files_c_chosen_symset_end; /* files.c: chosen_symset_end */
    boolean g_dlb_c_initialized; /* dlb.c: initialized */
    /* lazily-allocated per-env blobs whose types are private to one
     * .c file (e.g. options.c boolopt copy); freed by nh_ctx_free.
     * Slot assignments are documented at the allocation sites. */
    void *nh_lazy[NH_LAZY_SLOTS];
};

/* One game per process/dl-copy for now; becomes __thread when the
 * multi-env single-library step lands (see docs/DESIGN.md §2). */
extern struct nh_ctx *nh_cur;

struct nh_ctx *nh_ctx_new(void);
void nh_ctx_free(struct nh_ctx *);
/* handwritten (src/nh_ctx_fixup.c): fields whose initial value
 * points into the ctx itself, e.g. subrooms = &rooms[N]. */
void nh_ctx_fixup(struct nh_ctx *);

/* accessors: true globals (statics get per-file headers) */
#define moves (nh_cur->g_moves)
#define monstermoves (nh_cur->g_monstermoves)
#define multi (nh_cur->g_multi)
#define vision_full_recalc (nh_cur->g_vision_full_recalc)
#define viz_array (nh_cur->g_viz_array)
#define program_state (nh_cur->g_program_state)
#define occupation (nh_cur->g_occupation)
#define afternmv (nh_cur->g_afternmv)
#define hname (nh_cur->g_hname)
#define hackpid (nh_cur->g_hackpid)
#define locknum (nh_cur->g_locknum)
#define chosen_windowtype (nh_cur->g_chosen_windowtype)
#define bases (nh_cur->g_bases)
#define multi_reason (nh_cur->g_multi_reason)
#define nroom (nh_cur->g_nroom)
#define nsubroom (nh_cur->g_nsubroom)
#define occtime (nh_cur->g_occtime)
#define x_maze_max (nh_cur->g_x_maze_max)
#define y_maze_max (nh_cur->g_y_maze_max)
#define otg_temp (nh_cur->g_otg_temp)
#define in_doagain (nh_cur->g_in_doagain)
#define dungeon_topology (nh_cur->g_dungeon_topology)
#define quest_status (nh_cur->g_quest_status)
#define warn_obj_cnt (nh_cur->g_warn_obj_cnt)
#define smeq (nh_cur->g_smeq)
#define doorindex (nh_cur->g_doorindex)
#define save_cm (nh_cur->g_save_cm)
#define killer (nh_cur->g_killer)
#define done_money (nh_cur->g_done_money)
#define nomovemsg (nh_cur->g_nomovemsg)
#define plname (nh_cur->g_plname)
#define pl_character (nh_cur->g_pl_character)
#define pl_race (nh_cur->g_pl_race)
#define pl_fruit (nh_cur->g_pl_fruit)
#define ffruit (nh_cur->g_ffruit)
#define tune (nh_cur->g_tune)
#define ransacked (nh_cur->g_ransacked)
#define occtxt (nh_cur->g_occtxt)
#define yn_number (nh_cur->g_yn_number)
#define level_info (nh_cur->g_level_info)
#define tbx (nh_cur->g_tbx)
#define tby (nh_cur->g_tby)
#define m_shot (nh_cur->g_m_shot)
#define dungeons (nh_cur->g_dungeons)
#define sp_levchn (nh_cur->g_sp_levchn)
#define upstair (nh_cur->g_upstair)
#define dnstair (nh_cur->g_dnstair)
#define upladder (nh_cur->g_upladder)
#define dnladder (nh_cur->g_dnladder)
#define sstairs (nh_cur->g_sstairs)
#define updest (nh_cur->g_updest)
#define dndest (nh_cur->g_dndest)
#define inv_pos (nh_cur->g_inv_pos)
#define defer_see_monsters (nh_cur->g_defer_see_monsters)
#define in_mklev (nh_cur->g_in_mklev)
#define stoned (nh_cur->g_stoned)
#define unweapon (nh_cur->g_unweapon)
#define mrg_to_wielded (nh_cur->g_mrg_to_wielded)
#define in_steed_dismounting (nh_cur->g_in_steed_dismounting)
#define has_strong_rngseed (nh_cur->g_has_strong_rngseed)
#define bhitpos (nh_cur->g_bhitpos)
#define doors (nh_cur->g_doors)
#define rooms (nh_cur->g_rooms)
#define subrooms (nh_cur->g_subrooms)
#define upstairs_room (nh_cur->g_upstairs_room)
#define dnstairs_room (nh_cur->g_dnstairs_room)
#define sstairs_room (nh_cur->g_sstairs_room)
#define level (nh_cur->g_level)
#define ftrap (nh_cur->g_ftrap)
#define youmonst (nh_cur->g_youmonst)
#define context (nh_cur->g_context)
#define flags (nh_cur->g_flags)
#define iflags (nh_cur->g_iflags)
#define u (nh_cur->g_u)
#define ubirthday (nh_cur->g_ubirthday)
#define urealtime (nh_cur->g_urealtime)
#define lastseentyp (nh_cur->g_lastseentyp)
#define invent (nh_cur->g_invent)
#define uwep (nh_cur->g_uwep)
#define uarm (nh_cur->g_uarm)
#define uswapwep (nh_cur->g_uswapwep)
#define uquiver (nh_cur->g_uquiver)
#define uarmu (nh_cur->g_uarmu)
#define uskin (nh_cur->g_uskin)
#define uarmc (nh_cur->g_uarmc)
#define uarmh (nh_cur->g_uarmh)
#define uarms (nh_cur->g_uarms)
#define uarmg (nh_cur->g_uarmg)
#define uarmf (nh_cur->g_uarmf)
#define uamul (nh_cur->g_uamul)
#define uright (nh_cur->g_uright)
#define uleft (nh_cur->g_uleft)
#define ublindf (nh_cur->g_ublindf)
#define uchain (nh_cur->g_uchain)
#define uball (nh_cur->g_uball)
#define current_wand (nh_cur->g_current_wand)
#define thrownobj (nh_cur->g_thrownobj)
#define kickedobj (nh_cur->g_kickedobj)
#define spl_book (nh_cur->g_spl_book)
#define wailmsg (nh_cur->g_wailmsg)
#define migrating_objs (nh_cur->g_migrating_objs)
#define billobjs (nh_cur->g_billobjs)
#define dogname (nh_cur->g_dogname)
#define catname (nh_cur->g_catname)
#define horsename (nh_cur->g_horsename)
#define preferred_pet (nh_cur->g_preferred_pet)
#define mydogs (nh_cur->g_mydogs)
#define migrating_mons (nh_cur->g_migrating_mons)
#define apelist (nh_cur->g_apelist)
#define mvitals (nh_cur->g_mvitals)
#define domove_attempting (nh_cur->g_domove_attempting)
#define domove_succeeded (nh_cur->g_domove_succeeded)
#define menu_colorings (nh_cur->g_menu_colorings)
#define WIN_MESSAGE (nh_cur->g_WIN_MESSAGE)
#define WIN_STATUS (nh_cur->g_WIN_STATUS)
#define WIN_MAP (nh_cur->g_WIN_MAP)
#define WIN_INVEN (nh_cur->g_WIN_INVEN)
#define toplines (nh_cur->g_toplines)
#define tc_gbl_data (nh_cur->g_tc_gbl_data)
#define fqn_prefix (nh_cur->g_fqn_prefix)
#define sfcap (nh_cur->g_sfcap)
#define sfrestinfo (nh_cur->g_sfrestinfo)
#define sfsaveinfo (nh_cur->g_sfsaveinfo)
#define plinemsg_types (nh_cur->g_plinemsg_types)
#define nhUse_dummy (nh_cur->g_nhUse_dummy)
#define Cmd (nh_cur->g_Cmd)
#define xwaitingforspace (nh_cur->g_xwaitingforspace)
#define restoring (nh_cur->g_restoring)
#define notonhead (nh_cur->g_notonhead)
#define nle_seeds (nh_cur->g_nle_seeds)
#define symset_list (nh_cur->g_symset_list)

#endif /* NH_CTX_GEN_H */
