#!/usr/bin/env python3
"""Generate the per-env context from tools/globals.def.

Outputs (all fully generated — never edit by hand):
  include/nh_ctx_gen.h       struct nh_ctx (hot fields first), nh_cur extern,
                             lifecycle decls, accessor macros for true globals
  include/nh_ctx_files/*.h   accessor macros for file statics, one header per
                             migrated .c file (included only by that file)
  src/nh_ctx_gen.c           nh_cur definition, nh_ctx_new()/nh_ctx_free(),
                             .data template memcpys

Struct fields are prefixed g_ (g_<name> for globals, g_<file>_<name> for
statics) so accessor macros can never expand inside the struct definition
itself.

--check: regenerate to a scratch area and fail if outputs differ from what's
checked in (CI guard against stale generated files).
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEF = os.path.join(ROOT, "tools", "globals.def")

HEADER = "/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */\n"


def parse(path):
    entries = []
    with open(path) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            parts = [p.strip() for p in line.split("|")]
            if len(parts) != 6:
                sys.exit(f"{path}:{lineno}: expected 6 fields, got {len(parts)}")
            scope, heat, ctype, name, dims, init = parts
            if heat not in ("hot", "cold"):
                sys.exit(f"{path}:{lineno}: heat must be hot|cold")
            if init not in ("0", "1"):
                sys.exit(f"{path}:{lineno}: init must be 0|1")
            entries.append(
                dict(scope=scope, heat=heat, ctype=ctype, name=name,
                     dims=dims, init=init == "1", lineno=lineno)
            )
    seen = set()
    for e in entries:
        key = (e["scope"], e["name"])
        if key in seen:
            sys.exit(f"duplicate entry: {key}")
        seen.add(key)
    return entries


def field_name(e):
    if e["scope"] == "global":
        return f"g_{e['name']}"
    return f"g_{e['scope'].replace('.', '_').replace('-', '_')}_{e['name']}"


def file_key(scope):
    return scope.replace(".", "_").replace("-", "_")


def gen_struct_header(entries):
    out = [HEADER]
    out.append("#ifndef NH_CTX_GEN_H\n#define NH_CTX_GEN_H\n")
    out.append("#define NH_LAZY_SLOTS 64")
    out.append("struct nh_ctx {")
    out.append("    /* hot: touched every step; keep packed at the front so the")
    out.append("     * per-step working set spans the fewest cache lines. */")
    for heat in ("hot", "cold"):
        out.append(f"    /* --- {heat} --- */")
        chunk = [e for e in entries if e["heat"] == heat]
        if not chunk:
            out.append(f"    char nh_pad_{heat}_;")
        for e in chunk:
            if "{NAME}" in e["ctype"]:
                # full declarator with placeholder, e.g. 'int (*{NAME})(void)'
                decl = e["ctype"].replace("{NAME}", field_name(e))
                out.append(f"    {decl}; /* {e['scope']}: {e['name']} */")
            else:
                out.append(f"    {e['ctype']} {field_name(e)}{e['dims']}; /* {e['scope']}: {e['name']} */")
    out.append("    /* lazily-allocated per-env blobs whose types are private to one")
    out.append("     * .c file (e.g. options.c boolopt copy); freed by nh_ctx_free.")
    out.append("     * Slot assignments are documented at the allocation sites. */")
    out.append("    void *nh_lazy[NH_LAZY_SLOTS];")
    out.append("};\n")
    out.append("/* THE per-env context pointer: one thread-local slot, re-anchored at")
    out.append(" * every public API entry, so any pool thread can step any env.")
    out.append(" * Default TLS model (global-dynamic) works under Python's")
    out.append(" * dlopen-copy-per-env; define NH_TLS_INITIAL_EXEC for the single-lib")
    out.append(" * vecenv build (faster TLS access; needs the static TLS reserve). */")
    out.append("#ifndef NH_THREAD_LOCAL")
    out.append("#if defined(NH_TLS_INITIAL_EXEC) && defined(__linux__)")
    out.append("#define NH_THREAD_LOCAL __thread __attribute__((tls_model(\"initial-exec\")))")
    out.append("#else")
    out.append("#define NH_THREAD_LOCAL __thread")
    out.append("#endif")
    out.append("#endif")
    out.append("extern NH_THREAD_LOCAL struct nh_ctx *nh_cur;\n")
    out.append("struct nh_ctx *nh_ctx_new(void);")
    out.append("void nh_ctx_free(struct nh_ctx *);")
    out.append("/* handwritten (src/nh_ctx_fixup.c): fields whose initial value")
    out.append(" * points into the ctx itself, e.g. subrooms = &rooms[N]. */")
    out.append("void nh_ctx_fixup(struct nh_ctx *);\n")
    globals_ = [e for e in entries if e["scope"] == "global"]
    if globals_:
        out.append("/* accessors: true globals (statics get per-file headers) */")
        for e in globals_:
            out.append(f"#define {e['name']} (nh_cur->{field_name(e)})")
    out.append("\n#endif /* NH_CTX_GEN_H */")
    return "\n".join(out) + "\n"


def gen_file_headers(entries):
    files = {}
    for e in entries:
        if e["scope"] == "global":
            continue
        files.setdefault(e["scope"], []).append(e)
    result = {}
    for scope, es in sorted(files.items()):
        key = file_key(scope)
        guard = f"NH_CTX_FILE_{key.upper()}_H"
        out = [HEADER]
        out.append(f"/* Accessors for statics migrated out of {scope}.")
        out.append(f" * Include ONLY from {scope}, after hack.h. */")
        out.append(f"#ifndef {guard}\n#define {guard}")
        for e in es:
            out.append(f"#define {e['name']} (nh_cur->{field_name(e)})")
        out.append(f"#endif /* {guard} */")
        result[f"nh_ctx_files/{key}.h"] = "\n".join(out) + "\n"
    return result


def gen_impl(entries):
    out = [HEADER]
    out.append('#include <sys/mman.h> /* before hack.h: ctx accessor')
    out.append(' * macros (flags, ...) must not expand in libc headers */\n')
    out.append('#include "hack.h"\n')
    out.append("NH_THREAD_LOCAL struct nh_ctx *nh_cur;\n")
    inits = [e for e in entries if e["init"]]
    for e in inits:
        # postfix const so it binds to the whole declarator (matches
        # 'const char *const tmpl[N]' style template definitions)
        out.append(f"extern {e['ctype']} const nh_tmpl_{e['name']}{e['dims']};")
    out.append("")
    out.append("struct nh_ctx *")
    out.append("nh_ctx_new(void)")
    out.append("{")
    out.append("    /* mmap, not calloc: fresh kernel zero-pages every episode. A heap")
    out.append("     * chunk this size is reused dirty after nh_ctx_free, so calloc's")
    out.append("     * memset rewrites the whole struct through the cache each reset")
    out.append("     * (60% of all LL write misses at 341 envs); never-touched pages")
    out.append("     * also stay free under mmap. */")
    out.append("    size_t nh_sz = (sizeof(struct nh_ctx) + 4095) & ~(size_t) 4095;")
    out.append("    struct nh_ctx *nh = (struct nh_ctx *) mmap(")
    out.append("        NULL, nh_sz, PROT_READ | PROT_WRITE,")
    out.append("        MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);")
    out.append("    if (nh == MAP_FAILED)")
    out.append("        return (struct nh_ctx *) 0;")
    if inits:
        out.append("    /* restore non-zero initializers (.data templates) */")
        for e in inits:
            f = field_name(e)
            out.append(f"    memcpy(&nh->{f}, &nh_tmpl_{e['name']}, sizeof(nh->{f}));")
    out.append("    nh_ctx_fixup(nh);")
    out.append("    return nh;")
    out.append("}")
    out.append("")
    out.append("void")
    out.append("nh_ctx_free(struct nh_ctx *nh)")
    out.append("{")
    out.append("    int i;")
    out.append("    if (!nh)")
    out.append("        return;")
    out.append("    for (i = 0; i < NH_LAZY_SLOTS; i++)")
    out.append("        free(nh->nh_lazy[i]);")
    out.append("    munmap(nh, (sizeof(struct nh_ctx) + 4095) & ~(size_t) 4095);")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if checked-in outputs are stale")
    args = ap.parse_args()

    entries = parse(DEF)
    outputs = {
        "include/nh_ctx_gen.h": gen_struct_header(entries),
        "src/nh_ctx_gen.c": gen_impl(entries),
    }
    outputs.update(
        {f"include/{k}": v for k, v in gen_file_headers(entries).items()}
    )

    stale = []
    for rel, content in outputs.items():
        path = os.path.join(ROOT, rel)
        if args.check:
            try:
                with open(path) as f:
                    if f.read() != content:
                        stale.append(rel)
            except FileNotFoundError:
                stale.append(rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(content)
            print(f"wrote {rel}")

    if args.check:
        if stale:
            sys.exit("stale generated files (run tools/gen_ctx.py): "
                     + ", ".join(stale))
        print("generated files up to date")


if __name__ == "__main__":
    main()
