/* GENERATED by tools/gen_ctx.py from tools/globals.def — do not edit. */

#include "hack.h"

NH_THREAD_LOCAL struct nh_ctx *nh_cur;

extern long const nh_tmpl_moves;
extern long const nh_tmpl_monstermoves;
extern int const nh_tmpl_x_maze_max;
extern int const nh_tmpl_y_maze_max;
extern winid const nh_tmpl_WIN_MESSAGE;
extern winid const nh_tmpl_WIN_STATUS;
extern winid const nh_tmpl_WIN_MAP;
extern winid const nh_tmpl_WIN_INVEN;
extern struct savefile_info const nh_tmpl_sfcap;
extern struct savefile_info const nh_tmpl_sfsaveinfo;

struct nh_ctx *
nh_ctx_new(void)
{
    struct nh_ctx *nh = (struct nh_ctx *) calloc(1, sizeof(struct nh_ctx));
    if (!nh)
        return (struct nh_ctx *) 0;
    /* restore non-zero initializers (.data templates) */
    memcpy(&nh->g_moves, &nh_tmpl_moves, sizeof(nh->g_moves));
    memcpy(&nh->g_monstermoves, &nh_tmpl_monstermoves, sizeof(nh->g_monstermoves));
    memcpy(&nh->g_x_maze_max, &nh_tmpl_x_maze_max, sizeof(nh->g_x_maze_max));
    memcpy(&nh->g_y_maze_max, &nh_tmpl_y_maze_max, sizeof(nh->g_y_maze_max));
    memcpy(&nh->g_WIN_MESSAGE, &nh_tmpl_WIN_MESSAGE, sizeof(nh->g_WIN_MESSAGE));
    memcpy(&nh->g_WIN_STATUS, &nh_tmpl_WIN_STATUS, sizeof(nh->g_WIN_STATUS));
    memcpy(&nh->g_WIN_MAP, &nh_tmpl_WIN_MAP, sizeof(nh->g_WIN_MAP));
    memcpy(&nh->g_WIN_INVEN, &nh_tmpl_WIN_INVEN, sizeof(nh->g_WIN_INVEN));
    memcpy(&nh->g_sfcap, &nh_tmpl_sfcap, sizeof(nh->g_sfcap));
    memcpy(&nh->g_sfsaveinfo, &nh_tmpl_sfsaveinfo, sizeof(nh->g_sfsaveinfo));
    nh_ctx_fixup(nh);
    return nh;
}

void
nh_ctx_free(struct nh_ctx *nh)
{
    int i;
    if (!nh)
        return;
    for (i = 0; i < NH_LAZY_SLOTS; i++)
        free(nh->nh_lazy[i]);
    free(nh);
}
